package app.xylune.chat.ui

/** Additional Turkish copy for previews, provider details and low-frequency UI states. */
internal object TurkishUiCopyExtra2 {
    private val exact = mapOf(
        "Could not unlock archive" to "Arşivin kilidi açılamadı",
        "Reasoning details" to "Akıl yürütme ayrıntıları",
        "Open the creator's GitHub profile" to "Geliştiricinin GitHub profilini aç",
        "Open Xylune archive" to "Xylune arşivini aç",
        "Opened by Xylune" to "Xylune tarafından açıldı",
        "Opening Android's folder picker…" to "Android klasör seçici açılıyor…",
        "Opening backup preview…" to "Yedek önizlemesi açılıyor…",
        "Opening file picker…" to "Dosya seçici açılıyor…",
        "Optional download for tools that cannot run in bundled Python" to "Dahili Python'da çalışamayan araçlar için isteğe bağlı indirme",
        "Optional hybrid preflight counting. Provider count endpoints are preferred; local model-family estimates and the generic estimator are fallbacks." to "İsteğe bağlı hibrit ön kontrol sayımı. Sağlayıcının sayım uç noktaları tercih edilir; yerel model ailesi tahminleri ve genel tahminci yedek olarak kullanılır.",
        "Optional · cost will show as unavailable" to "İsteğe bağlı · maliyet kullanılamıyor olarak görünür",
        "Optional. Preview a local or cloud backup before importing anything." to "İsteğe bağlı. Herhangi bir şeyi içe aktarmadan önce yerel veya bulut yedeğini önizleyin.",
        "Original image • model receives OCR fallback" to "Özgün görsel • model OCR yedeğini alır",
        "Original image • selected model cannot receive it" to "Özgün görsel • seçili model bunu alamaz",
        "Output / billed tokens" to "Çıktı / faturalandırılan token'lar",
        "Override default tone/persona" to "Varsayılan üslup/personayı geçersiz kıl",
        "Package installation failed" to "Paket yüklemesi başarısız",
        "Packages and their installers run with Xylune's app permissions. Ubuntu is for compatibility, not containment; these settings intentionally reduce confirmation barriers." to "Paketler ve yükleyicileri Xylune'un uygulama izinleriyle çalışır. Ubuntu uyumluluk içindir, yalıtım için değil; bu ayarlar onay engellerini bilerek azaltır.",
        "Password or app password" to "Parola veya uygulama parolası",
        "Password — leave blank for none" to "Parola — kullanmayacaksanız boş bırakın",
        "Passwords do not match" to "Parolalar eşleşmiyor",
        "Per-response call breakdowns are available from each assistant message's ⋮ menu." to "Yanıt başına çağrı dökümleri her asistan mesajının ⋮ menüsünde bulunur.",
        "Plan ready for your confirmation." to "Plan onayınız için hazır.",
        "Portable cloud backups can include chats, app settings, organization, and optional Linux root filesystems. Passwordless backups are allowed after an explicit warning; API keys, OAuth sessions, provider authorization headers, cloud grants, and database encryption keys are excluded." to "Taşınabilir bulut yedekleri sohbetleri, uygulama ayarlarını, düzenlemeyi ve isteğe bağlı Linux kök dosya sistemlerini içerebilir. Açık bir uyarıdan sonra parolasız yedeklere izin verilir; API anahtarları, OAuth oturumları, sağlayıcı yetkilendirme başlıkları, bulut izinleri ve veritabanı şifreleme anahtarları hariç tutulur.",
        "Portable Xylune backup" to "Taşınabilir Xylune yedeği",
        "Preflight & review" to "Ön kontrol ve inceleme",
        "Preflight failed" to "Ön kontrol başarısız",
        "Preparing file" to "Dosya hazırlanıyor",
        "Preparing package plan…" to "Paket planı hazırlanıyor…",
        "Preparing query" to "Sorgu hazırlanıyor",
        "Preparing Xylune…" to "Xylune hazırlanıyor…",
        "Preset: Custom" to "Ön ayar: Özel",
        "Preview and import a backup" to "Yedeği önizle ve içe aktar",
        "Previous extracted-text page" to "Önceki çıkarılan metin sayfası",
        "Previous setup step" to "Önceki kurulum adımı",
        "Previous text page" to "Önceki metin sayfası",
        "Previously selected backup folder" to "Daha önce seçilen yedek klasörü",
        "Privacy, local data, providers, and KVKK/GDPR boundaries" to "Gizlilik, yerel veriler, sağlayıcılar ve KVKK/GDPR sınırları",
        "Private cloud targets" to "Özel bulut hedefleri",
        "Private Xylune app storage" to "Özel Xylune uygulama depolaması",
        "Profiler disabled" to "Profilleyici devre dışı",
        "Project website" to "Proje web sitesi",
        "Provider calls" to "Sağlayıcı çağrıları",
        "Provider details unavailable" to "Sağlayıcı ayrıntıları kullanılamıyor",
        "Provider has no model list? Enter manually" to "Sağlayıcının model listesi yok mu? Elle girin",
        "Provider is missing" to "Sağlayıcı eksik",
        "Provider name is required" to "Sağlayıcı adı gerekli",
        "Provider native search" to "Sağlayıcının yerel araması",
        "Provider preview" to "Sağlayıcı önizlemesi",
        "Provider search" to "Sağlayıcı araması",
        "Python and Linux share this chat's private /workspace. Runtime setup, packages, health, tests, and removal have one owner here." to "Python ve Linux bu sohbetin özel /workspace alanını paylaşır. Çalışma zamanı kurulumu, paketler, sağlık durumu, testler ve kaldırma burada tek yerden yönetilir.",
        "PYTHON CODE" to "PYTHON KODU",
        "Python is built in. Linux is an optional compatibility layer with a separate download. Pick a runtime only when you need to inspect or change it." to "Python yerleşiktir. Linux ayrı indirilen isteğe bağlı bir uyumluluk katmanıdır. Yalnızca incelemeniz veya değiştirmeniz gerektiğinde bir çalışma zamanı seçin.",
        "Python is still running" to "Python hâlâ çalışıyor",
        "Python result" to "Python sonucu",
        "Python script" to "Python betiği",
        "Python tool result" to "Python araç sonucu",
        "Python workspace" to "Python çalışma alanı",
        "Python · Ready" to "Python · Hazır",
        "Query ready" to "Sorgu hazır",
        "Query unavailable" to "Sorgu kullanılamıyor",
        "Queue image" to "Görseli sıraya al",
        "Queue this message" to "Bu mesajı sıraya al",
        "Raw token totals recorded from provider calls. Use these with the provider's current pricing when you want to verify or calculate cost manually." to "Sağlayıcı çağrılarından kaydedilen ham token toplamları. Maliyeti elle doğrulamak veya hesaplamak için bunları sağlayıcının güncel fiyatlarıyla kullanın.",
        "Read license" to "Lisansı oku",
        "Reading source" to "Kaynak okunuyor",
        "Reading source…" to "Kaynak okunuyor…",
        "Ready for your review" to "İncelemeniz için hazır",
        "Reference image" to "Referans görsel",
        "Refresh backup list" to "Yedek listesini yenile",
        "Regenerate chat name" to "Sohbet adını yeniden oluştur",
        "Release to snap to the nearest supported level" to "En yakın desteklenen düzeye oturtmak için bırakın",
        "Remove attachments first · image editing is not enabled yet" to "Önce ekleri kaldırın · görsel düzenleme henüz etkin değil",
        "Remove attachments to generate an image" to "Görsel oluşturmak için ekleri kaldırın",
        "Remove favorite" to "Favorilerden kaldır",
        "Remove Linux runtime" to "Linux çalışma zamanını kaldır",
        "Remove non-image attachments before creating an image." to "Görsel oluşturmadan önce görsel olmayan ekleri kaldırın.",
        "Rename provider" to "Sağlayıcıyı yeniden adlandır",
        "Render command issue" to "İşleme komutu sorunu",
        "Render sync" to "İşleme eşzamanlaması",
        "Rendering image" to "Görsel işleniyor",
        "Rendering PDF…" to "PDF işleniyor…",
        "Replaced by an edited message" to "Düzenlenmiş mesajla değiştirildi",
        "Replaced by retry" to "Yeniden denemeyle değiştirildi",
        "Request error" to "İstek hatası",
        "Request failed" to "İstek başarısız",
        "Request metadata" to "İstek meta verileri",
        "Request snapshots and extracted attachment metadata" to "İstek anlık görüntüleri ve çıkarılan ek meta verileri",
        "Requesting access to Google Drive app storage…" to "Google Drive uygulama depolamasına erişim isteniyor…",
        "Research in progress" to "Araştırma sürüyor",
        "Research request…" to "Araştırma isteği…",
        "Research roadmap" to "Araştırma yol haritası",
        "Research state reported" to "Araştırma durumu bildirildi",
        "Reset advanced values to defaults" to "Gelişmiş değerleri varsayılana sıfırla",
        "Response paused" to "Yanıt duraklatıldı",
        "Restore a backup" to "Bir yedeği geri yükle",
        "Restore an existing setup" to "Mevcut kurulumu geri yükle",
        "Restrained blue-gray palette" to "Sade mavi-gri palet",
        "Result exposed by the model provider's search response." to "Model sağlayıcısının arama yanıtında sunulan sonuç.",
        "Retry response" to "Yanıtı yeniden dene",
        "Retry setup" to "Kurulumu yeniden dene",
        "Review and install changes" to "Değişiklikleri incele ve yükle",
        "Run details" to "Çalıştırma ayrıntıları",
        "Run failed" to "Çalıştırma başarısız",
        "Run in workspace" to "Çalışma alanında çalıştır",
        "Run preflight again" to "Ön kontrolü yeniden çalıştır",
        "Run Python in this chat's persistent workspace" to "Python'u bu sohbetin kalıcı çalışma alanında çalıştır",
        "Run with Linux tools" to "Linux araçlarıyla çalıştır",
        "Running on" to "Çalıştığı sürüm",
        "Running…" to "Çalışıyor…",
        "running…" to "çalışıyor…",
        "S3-compatible storage" to "S3 uyumlu depolama",
        "Safe defaults share visible messages and attachments. Hidden reasoning, tool diagnostics, prompts, and request snapshots stay excluded until you enable them." to "Güvenli varsayılanlar görünür mesajları ve ekleri paylaşır. Gizli akıl yürütme, araç tanılamaları, istemler ve istek anlık görüntüleri siz etkinleştirene kadar hariç kalır.",
        "Save & regenerate" to "Kaydet ve yeniden oluştur",
        "Save a copy" to "Bir kopya kaydet",
        "Save and test" to "Kaydet ve test et",
        "Save backup" to "Yedeği kaydet",
        "saved history" to "kaydedilmiş geçmiş",
        "Search across every chat" to "Tüm sohbetlerde ara",
        "Search chat models by name, ID, provider, or description" to "Sohbet modellerinde ada, kimliğe, sağlayıcıya veya açıklamaya göre ara",
        "Search failed" to "Arama başarısız",
        "Search history" to "Arama geçmişi",
        "Search image models" to "Görsel modellerinde ara",
        "Search libraries or licenses" to "Kitaplık veya lisanslarda ara",
        "Search messages, code, and reasoning" to "Mesaj, kod ve akıl yürütmede ara",
        "Search off" to "Arama kapalı",
        "Search PyPI" to "PyPI'da ara",
        "Searching…" to "Aranıyor…",
        "Secret access key" to "Gizli erişim anahtarı",
        "Selectable extracted content" to "Seçilebilir çıkarılmış içerik",
        "Selectable file preview" to "Seçilebilir dosya önizlemesi",
        "Selectable OCR text" to "Seçilebilir OCR metni",
        "Selected cloud folder" to "Seçili bulut klasörü",
        "Selected model cannot read the original attachment" to "Seçili model özgün eki okuyamıyor",
        "Send after the current response finishes" to "Mevcut yanıt bitince gönder",
        "Send now" to "Şimdi gönder",
        "Send options" to "Gönderme seçenekleri",
        "Sent file" to "Gönderilen dosya",
        "Session token (optional)" to "Oturum token'ı (isteğe bağlı)",
        "Set up a provider" to "Bir sağlayıcı kur",
        "Set up a provider to start" to "Başlamak için bir sağlayıcı kur",
        "Set up provider" to "Sağlayıcıyı kur",
        "Settings stay optional" to "Ayarlar isteğe bağlı kalır",
        "Share message" to "Mesajı paylaş",
        "Share Xylune chat" to "Xylune sohbetini paylaş",
        "SHELL COMMAND" to "KABUK KOMUTU",
        "Short reasoning" to "Kısa akıl yürütme",
        "Show backups" to "Yedekleri göster",
        "Show complete package plan" to "Tam paket planını göster",
        "Show package plan" to "Paket planını göster",
        "Show source" to "Kaynağı göster",
        "Shows live frame timing without forcing continuous animation. The monitor observes frames already rendered by Android." to "Sürekli animasyonu zorlamadan canlı kare zamanlamasını gösterir. İzleyici Android tarafından zaten işlenmiş kareleri gözlemler.",
        "Shows raw tool inputs, outputs, source paths, and copyable failure diagnostics inside Working." to "Çalışma içinde ham araç girdilerini, çıktıları, kaynak yollarını ve kopyalanabilir hata tanılamalarını gösterir.",
        "Sign in without pasting an API key." to "API anahtarı yapıştırmadan oturum açın.",
        "Sign in; Xylune only uses its app folder" to "Oturum açın; Xylune yalnızca uygulama klasörünü kullanır",
        "Signing SHA-1" to "İmzalama SHA-1",
        "Source failed" to "Kaynak başarısız",
        "Source read" to "Kaynak okundu",
        "Source read completed" to "Kaynak okuma tamamlandı",
        "Source request ready" to "Kaynak isteği hazır",
        "Start a response" to "Yanıt başlat",
        "Starting package installation" to "Paket yükleme başlatılıyor",
        "Steer current response" to "Mevcut yanıtı yönlendir",
        "Steered by user" to "Kullanıcı tarafından yönlendirildi",
        "Stop current response" to "Mevcut yanıtı durdur",
        "Stop image generation" to "Görsel oluşturmayı durdur",
        "Stopped by user" to "Kullanıcı tarafından durduruldu",
        "Streaming…" to "Akış sürüyor…",
        "Switch account" to "Hesap değiştir",
        "Switched branch" to "Dal değiştirildi",
        "Switched to another branch" to "Başka bir dala geçildi",
        "Take a photo and attach it" to "Fotoğraf çek ve ekle",
        "Take a photo to use as a reference" to "Referans olarak kullanmak için fotoğraf çek",
        "Tap a result to add it to the install list" to "Yükleme listesine eklemek için bir sonuca dokunun",
        "Tap to zoom" to "Yakınlaştırmak için dokun",
        "Terminal, native CLI tools, and Linux packages" to "Terminal, yerel CLI araçları ve Linux paketleri",
        "The Android document picker can save directly to Google Drive, OneDrive, Dropbox, Nextcloud, a USB drive, or local storage. Xylune does not upload through a hidden server." to "Android belge seçici doğrudan Google Drive, OneDrive, Dropbox, Nextcloud, USB sürücü veya yerel depolamaya kaydedebilir. Xylune gizli bir sunucu üzerinden yükleme yapmaz.",
        "The built-in provider catalog is delayed. Setup remains usable and Xylune will keep retrying in the background." to "Yerleşik sağlayıcı kataloğu gecikiyor. Kurulum kullanılabilir kalır ve Xylune arka planda yeniden denemeye devam eder.",
        "The edited source is compiled, executed in the bounded runtime, and rendered before use." to "Düzenlenen kaynak kullanılmadan önce derlenir, sınırlandırılmış çalışma zamanında yürütülür ve işlenir.",
        "The embedded license document could not be opened." to "Gömülü lisans belgesi açılamadı.",
        "The exact prompt bundled with this app version is shown below. It is selectable for inspection and intentionally read-only." to "Bu uygulama sürümüyle birlikte gelen tam istem aşağıda gösterilir. İncelemek için seçilebilir ve özellikle salt okunurdur.",
        "The overlay explicitly shares pointer input with the content underneath and never consumes it. Taps, scrolling, drawer gestures, and back navigation continue through the panel." to "Katman işaretçi girdisini altındaki içerikle açıkça paylaşır ve asla tüketmez. Dokunma, kaydırma, çekmece hareketleri ve geri gezinme panel üzerinden çalışmaya devam eder.",
        "The previous install failed. Review before retrying." to "Önceki yükleme başarısız. Yeniden denemeden önce inceleyin.",
        "The previous install was interrupted. Review before retrying." to "Önceki yükleme kesintiye uğradı. Yeniden denemeden önce inceleyin.",
        "The provider exposed the query but did not return result metadata or citations." to "Sağlayıcı sorguyu sundu ancak sonuç meta verilerini veya kaynakları döndürmedi.",
        "The provider returned no models" to "Sağlayıcı model döndürmedi",
        "The provider stream failed without returning additional diagnostic text." to "Sağlayıcı akışı ek tanılama metni döndürmeden başarısız oldu.",
        "The response stopped before it completed." to "Yanıt tamamlanmadan durdu.",
        "The reviewed plan is no longer available. Run preflight again." to "İncelenen plan artık kullanılamıyor. Ön kontrolü yeniden çalıştırın.",
        "The source and conversation are intact." to "Kaynak ve sohbet sağlam.",
        "The Xylune maintainer does not create, train, host, pre-review, or endorse individual model outputs. AI output can be wrong, unsafe, biased, or unsuitable; verify it before relying on it. Provider terms, fees, retention, and content rules apply independently." to "Xylune geliştiricisi tek tek model çıktılarını oluşturmaz, eğitmez, barındırmaz, önceden incelemez veya onaylamaz. Yapay zekâ çıktıları yanlış, güvensiz, önyargılı veya uygunsuz olabilir; güvenmeden önce doğrulayın. Sağlayıcı koşulları, ücretleri, saklama ve içerik kuralları bağımsız olarak geçerlidir.",
        "These providers keep Xylune backups in an app-specific folder or prefix. OAuth tokens and storage credentials are encrypted on this device and excluded from exported backups." to "Bu sağlayıcılar Xylune yedeklerini uygulamaya özel bir klasör veya önekte tutar. OAuth token'ları ve depolama kimlik bilgileri bu cihazda şifrelenir ve dışa aktarılan yedeklere dahil edilmez.",
        "Thinking always on" to "Düşünme her zaman açık",
        "This attempt continued in the newer step below." to "Bu deneme aşağıdaki daha yeni adımda devam etti.",
        "This build has no GitHub source provenance" to "Bu derlemede GitHub kaynak kökeni yok",
        "This build is missing its generated offline notices." to "Bu derlemede oluşturulmuş çevrimdışı bildirimler eksik.",
        "This file is encrypted. Enter its password to inspect it." to "Bu dosya şifreli. İncelemek için parolasını girin.",
        "This location is connected, but it does not contain a Xylune backup yet." to "Bu konum bağlı ancak henüz Xylune yedeği içermiyor.",
        "This model cannot read the original attachment. OCR fallback will be prepared before sending." to "Bu model özgün eki okuyamıyor. Göndermeden önce OCR yedeği hazırlanacak.",
        "This model does not accept reference images." to "Bu model referans görsel kabul etmiyor.",
        "This model doesn't support tool calling. Web, Python, and Linux tools won't run." to "Bu model araç çağrısını desteklemiyor. Web, Python ve Linux araçları çalışmaz.",
        "This model receives OCR text and coordinates; you still see the untouched original." to "Bu model OCR metnini ve koordinatlarını alır; siz değiştirilmemiş özgün dosyayı görmeye devam edersiniz.",
        "This PDF could not be rendered" to "Bu PDF işlenemedi",
        "This provider returns the final image when generation finishes." to "Bu sağlayıcı oluşturma bittiğinde son görseli döndürür.",
        "This removes the selected Linux root filesystem and its installed packages for all chats. Chat files in /workspace and bundled Python packages are kept." to "Bu işlem seçili Linux kök dosya sistemini ve yüklü paketlerini tüm sohbetler için kaldırır. /workspace içindeki sohbet dosyaları ve dahili Python paketleri korunur.",
        "This saved package request already completed successfully." to "Bu kaydedilmiş paket isteği zaten başarıyla tamamlandı.",
        "Token fields are stored from provider usage metadata when the provider reports them. Otherwise Xylune may fall back to its local counter/estimator. Use the raw token counts above with your provider's current pricing table for manual calculation." to "Sağlayıcı bildirdiğinde token alanları kullanım meta verilerinden saklanır. Aksi halde Xylune yerel sayaç/tahminciyi kullanabilir. Elle hesaplama için yukarıdaki ham token sayılarını sağlayıcınızın güncel fiyat tablosuyla kullanın.",
        "Tool completed" to "Araç tamamlandı",
        "Tool output" to "Araç çıktısı",
        "Tool traces" to "Araç izleri",
        "Tool traces and working timeline" to "Araç izleri ve çalışma zaman çizelgesi",
        "Tools available to Xylune in this chat" to "Bu sohbette Xylune'un kullanabildiği araçlar",
        "Try a different word or a shorter phrase." to "Farklı bir kelime veya daha kısa bir ifade deneyin.",
        "Try a library name such as SQLCipher or a license such as Apache-2.0." to "SQLCipher gibi bir kitaplık adı veya Apache-2.0 gibi bir lisans deneyin.",
        "Try another provider or clear the current filters." to "Başka bir sağlayıcı deneyin veya mevcut filtreleri temizleyin.",
        "Try full rendering" to "Tam işlemeyi dene",
        "Type a message or attach a file first" to "Önce bir mesaj yazın veya dosya ekleyin",
        "Ubuntu result" to "Ubuntu sonucu",
        "Ubuntu tool result" to "Ubuntu araç sonucu",
        "UI draw / recording" to "Arayüz çizimi / kaydı",
        "Unavailable / calculate manually" to "Kullanılamıyor / elle hesaplayın",
        "Unavailable in this build • tap for details" to "Bu derlemede kullanılamıyor • ayrıntılar için dokunun",
        "Unlock preview" to "Önizlemenin kilidini aç",
        "Use a key restricted to this bucket and prefix. Credentials remain encrypted on-device." to "Bu bucket ve önekle sınırlandırılmış bir anahtar kullanın. Kimlik bilgileri cihazda şifreli kalır.",
        "Use chart JSON or `label: value` lines." to "Grafik JSON'u veya `etiket: değer` satırları kullanın.",
        "Use connected folder" to "Bağlı klasörü kullan",
        "Use custom instruction profiles for additional tone and workflow preferences." to "Ek üslup ve iş akışı tercihleri için özel talimat profillerini kullanın.",
        "Use OpenAI, Anthropic, Gemini, DeepSeek, or another compatible endpoint." to "OpenAI, Anthropic, Gemini, DeepSeek veya başka uyumlu bir uç nokta kullanın.",
        "Use terms, third-party AI limits, warranty, and liability" to "Kullanım koşulları, üçüncü taraf yapay zekâ sınırları, garanti ve sorumluluk",
        "Uses Dropbox App folder access and scoped file permissions. Xylune cannot browse the rest of Dropbox." to "Dropbox uygulama klasörü erişimini ve kapsamlı dosya izinlerini kullanır. Xylune Dropbox'ın geri kalanına göz atamaz.",
        "Uses OneDrive's Apps/Xylune folder with Files.ReadWrite.AppFolder instead of access to the whole drive." to "Tüm sürücüye erişmek yerine OneDrive'ın Apps/Xylune klasörünü Files.ReadWrite.AppFolder ile kullanır.",
        "Uses only Drive's hidden appDataFolder. Connect once, then create, browse, preview, and restore backups without repeating the consent flow." to "Yalnızca Drive'ın gizli appDataFolder alanını kullanır. Bir kez bağlandıktan sonra izin akışını tekrarlamadan yedek oluşturabilir, göz atabilir, önizleyebilir ve geri yükleyebilirsiniz.",
        "Waiting for Google Drive approval…" to "Google Drive onayı bekleniyor…",
        "Waiting for output…" to "Çıktı bekleniyor…",
        "Waiting for search results…" to "Arama sonuçları bekleniyor…",
        "Waiting for sign-in to finish" to "Oturum açmanın tamamlanması bekleniyor",
        "Waiting for the first provider-rendered preview…" to "Sağlayıcının ilk önizlemesi bekleniyor…",
        "Warm orange, rose, and gold accents" to "Sıcak turuncu, gül ve altın vurgular",
        "WebDAV / Nextcloud" to "WebDAV / Nextcloud",
        "WebDAV folder URL" to "WebDAV klasör URL'si",
        "Weekly limit" to "Haftalık sınır",
        "What are we creating?" to "Ne oluşturuyoruz?",
        "What are we working on?" to "Ne üzerinde çalışıyoruz?",
        "What this screen manages" to "Bu ekranın yönettikleri",
        "While Xylune is working" to "Xylune çalışırken",
        "Within frame budget" to "Kare bütçesi içinde",
        "Work complete" to "Çalışma tamamlandı",
        "Working-history token budget" to "Çalışma geçmişi token bütçesi",
        "Works with AWS S3, Cloudflare R2, Backblaze B2, MinIO, and other Signature V4-compatible object stores." to "AWS S3, Cloudflare R2, Backblaze B2, MinIO ve diğer Signature V4 uyumlu nesne depolarıyla çalışır.",
        "Works with Drive, OneDrive, Dropbox, Nextcloud, USB, local storage, and other Android document providers." to "Drive, OneDrive, Dropbox, Nextcloud, USB, yerel depolama ve diğer Android belge sağlayıcılarıyla çalışır.",
        "Writing report" to "Rapor yazılıyor",
        "Writing source request…" to "Kaynak isteği yazılıyor…",
        "Xylune adds request-specific date, enabled-tool, research, memory, attachment, and generated-content instructions at runtime. Those dynamic layers are not editable either and are not presented as one misleading static block." to "Xylune çalışma zamanında isteğe özel tarih, etkin araç, araştırma, hafıza, ek ve oluşturulan içerik talimatları ekler. Bu dinamik katmanlar da düzenlenemez ve yanıltıcı tek bir statik blok olarak sunulmaz.",
        "Xylune asks for the non-sensitive drive.appdata scope only. The backup files remain hidden from normal Drive browsing and from other apps." to "Xylune yalnızca hassas olmayan drive.appdata kapsamını ister. Yedek dosyaları normal Drive gezintisinden ve diğer uygulamalardan gizli kalır.",
        "Xylune cannot send messages until ChatGPT, an API provider, or a local model server is connected." to "ChatGPT, bir API sağlayıcısı veya yerel model sunucusu bağlanana kadar Xylune mesaj gönderemez.",
        "Xylune chat" to "Xylune sohbeti",
        "Xylune cloud folder connected" to "Xylune bulut klasörü bağlandı",
        "Xylune includes each installed root filesystem, packages, and configuration. Permissions, symbolic links, and hard links are preserved. This can make the backup several gigabytes." to "Xylune her yüklü kök dosya sistemini, paketleri ve yapılandırmayı dahil eder. İzinler, sembolik bağlantılar ve sabit bağlantılar korunur. Bu, yedeği birkaç gigabayt büyütebilir.",
        "Xylune is ready" to "Xylune hazır",
        "Xylune stores memories in its encrypted local database and selects only relevant items under a strict context budget. Disabled memories remain stored but are not supplied to models." to "Xylune hafızaları şifreli yerel veritabanında saklar ve sıkı bir bağlam bütçesi altında yalnızca ilgili öğeleri seçer. Devre dışı hafızalar saklanmaya devam eder ancak modellere verilmez.",
        "Xylune stream error" to "Xylune akış hatası",
    )

    fun translate(text: String): String {
        exact[text]?.let { return it }

        Regex("""Opening (.+) sign-in…""").matchEntire(text)?.let { return "${it.groupValues[1]} oturum açma sayfası açılıyor…" }
        Regex("""Page (\d+) of (\d+)""").matchEntire(text)?.let { return "${it.groupValues[2]} sayfanın ${it.groupValues[1]}. sayfası" }
        Regex("""PDF page (\d+)""").matchEntire(text)?.let { return "PDF sayfası ${it.groupValues[1]}" }
        Regex("""PDF preview unavailable: (.+)""").matchEntire(text)?.let { return "PDF önizlemesi kullanılamıyor: ${it.groupValues[1]}" }
        Regex("""Preview unavailable: (.+)""").matchEntire(text)?.let { return "Önizleme kullanılamıyor: ${it.groupValues[1]}" }
        Regex("""Preparing another (.+) build…""").matchEntire(text)?.let { return "Başka bir ${it.groupValues[1]} derlemesi hazırlanıyor…" }
        Regex("""Refresh failed • (.+)""").matchEntire(text)?.let { return "Yenileme başarısız • ${it.groupValues[1]}" }
        Regex("""Remove (.+)\?""").matchEntire(text)?.let { return "${it.groupValues[1]} kaldırılsın mı?" }
        Regex("""Share (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} paylaş" }
        Regex("""Series (\d+)""").matchEntire(text)?.let { return "Seri ${it.groupValues[1]}" }
        Regex("""Step (\d+) of (\d+)""").matchEntire(text)?.let { return "${it.groupValues[2]} adımın ${it.groupValues[1]}. adımı" }
        Regex("""Run failed with exit code (\d+)""").matchEntire(text)?.let { return "Çalıştırma ${it.groupValues[1]} çıkış koduyla başarısız oldu" }
        Regex("""Updated (\d+) models for (.+)""").matchEntire(text)?.let { return "${it.groupValues[2]} için ${it.groupValues[1]} model güncellendi" }
        Regex("""Waiting for (.+) authorization…""").matchEntire(text)?.let { return "${it.groupValues[1]} yetkilendirmesi bekleniyor…" }
        Regex("""Waiting for (.+) sign-in to finish…""").matchEntire(text)?.let { return "${it.groupValues[1]} oturum açma işleminin tamamlanması bekleniyor…" }
        Regex("""Xylune (.+) is available from (.+)""").matchEntire(text)?.let { return "Xylune ${it.groupValues[1]}, ${it.groupValues[2]} üzerinden kullanılabilir" }
        Regex("""Xylune (.+) is available""").matchEntire(text)?.let { return "Xylune ${it.groupValues[1]} kullanılabilir" }
        return text
    }
}
