package app.xylune.chat.ui

/** Less-common Turkish UI strings: errors, backup flows, runtime states and previews. */
internal object TurkishUiCopyExtra {
    private val exact = mapOf(
        "Confirm password" to "Parolayı doğrula",
        "Connect & fetch models" to "Bağlan ve modelleri getir",
        "Connect folder" to "Klasörü bağla",
        "Connect Google Drive" to "Google Drive'ı bağla",
        "Connect to Ollama, llama.cpp, or LM Studio." to "Ollama, llama.cpp veya LM Studio'ya bağlanın.",
        "Connection details stay out of the way until you need them." to "Bağlantı ayrıntıları gerekene kadar gizli kalır.",
        "Connection failed • tap to retry" to "Bağlantı başarısız • yeniden denemek için dokunun",
        "Controls whether reasoning and tool cards expand automatically; they remain saved either way." to "Akıl yürütme ve araç kartlarının otomatik açılıp açılmayacağını belirler; her durumda kaydedilmeye devam ederler.",
        "Conversation deleted" to "Sohbet silindi",
        "Cool teal and cyan accents" to "Soğuk turkuaz ve camgöbeği vurgular",
        "Copy errors" to "Hataları kopyala",
        "Copy setup details" to "Kurulum ayrıntılarını kopyala",
        "Copy source" to "Kaynağı kopyala",
        "cost unavailable" to "maliyet kullanılamıyor",
        "Could not connect the cloud folder" to "Bulut klasörüne bağlanılamadı",
        "Could not create the chat file" to "Sohbet dosyası oluşturulamadı",
        "Could not delete backup" to "Yedek silinemedi",
        "Could not download and inspect the cloud backup" to "Bulut yedeği indirilemedi veya incelenemedi",
        "Could not download backup" to "Yedek indirilemedi",
        "Could not fetch the model list" to "Model listesi getirilemedi",
        "Could not inspect archive" to "Arşiv incelenemedi",
        "Could not list backups" to "Yedekler listelenemedi",
        "Could not open backup" to "Yedek açılamadı",
        "Could not open cloud sign-in" to "Bulut oturum açma sayfası açılamadı",
        "Could not open the update link" to "Güncelleme bağlantısı açılamadı",
        "Could not read Google Drive app storage" to "Google Drive uygulama depolaması okunamadı",
        "Could not read the cloud folder" to "Bulut klasörü okunamadı",
        "Could not read the connected cloud folder" to "Bağlı bulut klasörü okunamadı",
        "Could not read the selected cloud folder" to "Seçili bulut klasörü okunamadı",
        "Could not unlock archive" to "Arşidin kilidi açılamadı",
        "Create image" to "Görsel oluştur",
        "Creating and uploading…" to "Oluşturuluyor ve yükleniyor…",
        "Credentials are encrypted with Android Keystore and are never included in Xylune backups." to "Kimlik bilgileri Android Keystore ile şifrelenir ve Xylune yedeklerine hiçbir zaman dahil edilmez.",
        "Credentials are encrypted with Android Keystore and sent only to the provider you choose." to "Kimlik bilgileri Android Keystore ile şifrelenir ve yalnızca seçtiğiniz sağlayıcıya gönderilir.",
        "Credits: unlimited" to "Krediler: sınırsız",
        "Custom system prompt" to "Özel sistem istemi",
        "Deep purple with soft rose accents" to "Yumuşak gül vurgulu koyu mor",
        "Delete backup" to "Yedeği sil",
        "Delete cloud backup?" to "Bulut yedeği silinsin mi?",
        "Delete local data and provider-held copies" to "Yerel verileri ve sağlayıcıdaki kopyaları sil",
        "Delete memory" to "Hafızayı sil",
        "Deleted system prompt" to "Sistem istemi silindi",
        "Describe an image to generate…" to "Oluşturulacak görseli açıklayın…",
        "Describe an image…" to "Bir görsel açıklayın…",
        "Describe the changes…" to "Değişiklikleri açıklayın…",
        "Describe the image you want to create." to "Oluşturmak istediğiniz görseli açıklayın.",
        "Describe the image you want. This model generates new images without reference-image editing." to "İstediğiniz görseli açıklayın. Bu model referans görsel düzenlemeden yeni görseller oluşturur.",
        "Development disclosure & disclaimer" to "Geliştirme açıklaması ve sorumluluk reddi",
        "Diagram renderer found no supported nodes" to "Diyagram işleyici desteklenen düğüm bulamadı",
        "DIAGRAM • native" to "DİYAGRAM • yerel",
        "Direct app storage" to "Doğrudan uygulama depolaması",
        "Direct HTTPS WebDAV support for Nextcloud, ownCloud, NAS servers, and compatible hosts. Use an app password when available." to "Nextcloud, ownCloud, NAS sunucuları ve uyumlu ana makineler için doğrudan HTTPS WebDAV desteği. Mümkünse uygulama parolası kullanın.",
        "Disable only for a trusted local or keyless endpoint" to "Yalnızca güvenilir yerel veya anahtarsız bir uç nokta için kapatın",
        "Disable only for your own local/keyless endpoint" to "Yalnızca kendi yerel/anahtarsız uç noktanız için kapatın",
        "Dismiss error" to "Hatayı kapat",
        "Display-only Markdown cannot edit generated content" to "Salt görüntüleme Markdown oluşturulan içeriği düzenleyemez",
        "Display-only Markdown cannot execute Linux tools" to "Salt görüntüleme Markdown Linux araçlarını çalıştıramaz",
        "Display-only Markdown cannot execute Python" to "Salt görüntüleme Markdown Python çalıştıramaz",
        "Display-only Markdown cannot install packages" to "Salt görüntüleme Markdown paket yükleyemez",
        "Display-only Markdown cannot repair generated content" to "Salt görüntüleme Markdown oluşturulan içeriği onaramaz",
        "Display-only Markdown cannot review packages" to "Salt görüntüleme Markdown paketleri inceleyemez",
        "Display-only Markdown cannot run widgets" to "Salt görüntüleme Markdown widget çalıştıramaz",
        "Distribution selection, installation, packages, and removal are managed in one place." to "Dağıtım seçimi, kurulum, paketler ve kaldırma tek bir yerden yönetilir.",
        "Documents, archives, code, audio, and other supported files" to "Belgeler, arşivler, kod, ses ve desteklenen diğer dosyalar",
        "Double-tap, pinch, or drag" to "Çift dokunun, sıkıştırın veya sürükleyin",
        "Draws explicit debug guides at the top and bottom panel boundaries. Normal UI no longer draws a boundary highlight." to "Üst ve alt panel sınırlarında belirgin hata ayıklama kılavuzları çizer. Normal arayüz artık sınır vurgusu çizmez.",
        "Dropbox Xylune App folder" to "Dropbox Xylune uygulama klasörü",
        "Duplicate content recording for blur" to "Bulanıklık için yinelenen içerik kaydı",
        "Each chat has a persistent bundled-Python session and isolated .packages directory. It works without installing Linux and remains confined by Android's app sandbox." to "Her sohbetin kalıcı bir dahili Python oturumu ve yalıtılmış .packages dizini vardır. Linux yüklemeden çalışır ve Android uygulama sanal alanı içinde kalır.",
        "Each provider keeps its OAuth session, models, usage limits, and refresh state separate. Xylune requests a fresh sign-in page so you can add a different ChatGPT account." to "Her sağlayıcı OAuth oturumunu, modellerini, kullanım sınırlarını ve yenileme durumunu ayrı tutar. Farklı bir ChatGPT hesabı ekleyebilmeniz için Xylune yeni bir oturum açma sayfası ister.",
        "Edit image" to "Görseli düzenle",
        "Edit images" to "Görselleri düzenle",
        "Edit memory" to "Hafızayı düzenle",
        "Edit message" to "Mesajı düzenle",
        "Edit source" to "Kaynağı düzenle",
        "Encryption password (optional)" to "Şifreleme parolası (isteğe bağlı)",
        "Enter a server folder and credentials" to "Sunucu klasörü ve kimlik bilgilerini girin",
        "Enter the exact HTTPS URL of a dedicated Xylune folder. For Nextcloud this normally ends with /remote.php/dav/files/USERNAME/Xylune/." to "Özel bir Xylune klasörünün tam HTTPS URL'sini girin. Nextcloud için bu genellikle /remote.php/dav/files/KULLANICI_ADI/Xylune/ ile biter.",
        "Enter Xylune now. You can return to Providers & models from Settings at any time." to "Şimdi Xylune'a girin. İstediğiniz zaman Ayarlar'dan Sağlayıcılar ve modeller bölümüne dönebilirsiniz.",
        "Everything listed here is embedded in this build and available without a network connection." to "Burada listelenen her şey bu derlemeye gömülüdür ve ağ bağlantısı olmadan kullanılabilir.",
        "Everything requested is already installed." to "İstenen her şey zaten yüklü.",
        "Exact provider counters where available, then local family and generic fallbacks." to "Varsa sağlayıcının kesin sayaçları, ardından yerel aile ve genel yedek değerler kullanılır.",
        "Execution completed" to "Çalıştırma tamamlandı",
        "Execution deadline (seconds)" to "Çalıştırma süre sınırı (saniye)",
        "Execution exceeded its configured deadline." to "Çalıştırma yapılandırılmış süre sınırını aştı.",
        "Execution failed" to "Çalıştırma başarısız",
        "Expand step" to "Adımı genişlet",
        "Expand work details" to "Çalışma ayrıntılarını genişlet",
        "Extended reasoning" to "Genişletilmiş akıl yürütme",
        "Fastest, light reasoning" to "En hızlı, hafif akıl yürütme",
        "Fetched source" to "Kaynak getirildi",
        "Fetching OpenRouter capabilities, reasoning modes, limits, and pricing…" to "OpenRouter yetenekleri, akıl yürütme modları, sınırlar ve fiyatlandırma getiriliyor…",
        "File no longer exists" to "Dosya artık mevcut değil",
        "Finished with an error" to "Hatayla tamamlandı",
        "Fit image" to "Görseli sığdır",
        "Focused defaults" to "Odaklanmış varsayılanlar",
        "Folder selection was cancelled." to "Klasör seçimi iptal edildi.",
        "Frame pacing / scheduling stalls" to "Kare zamanlama / planlama takılmaları",
        "Generate + edit" to "Oluştur + düzenle",
        "Generate image" to "Görsel oluştur",
        "Generate images" to "Görseller oluştur",
        "Generating image" to "Görsel oluşturuluyor",
        "GitHub release workflows embed their own owner/repository. Fork builds therefore follow the fork they came from." to "GitHub sürüm iş akışları kendi sahip/depo bilgisini içerir. Bu nedenle fork derlemeleri geldikleri fork'u takip eder.",
        "Global answer preferences. Changes apply to existing chats and new chats on their next response." to "Genel yanıt tercihleri. Değişiklikler mevcut ve yeni sohbetlere bir sonraki yanıtlarında uygulanır.",
        "Go to latest message" to "En son mesaja git",
        "Google account selected" to "Google hesabı seçildi",
        "Google Drive app storage" to "Google Drive uygulama depolaması",
        "Google Drive authorization could not be opened" to "Google Drive yetkilendirmesi açılamadı",
        "Google Drive authorization could not be opened." to "Google Drive yetkilendirmesi açılamadı.",
        "Google Drive authorization expired" to "Google Drive yetkilendirmesinin süresi doldu",
        "Google Drive authorization failed" to "Google Drive yetkilendirmesi başarısız",
        "Google Drive authorization returned no access token" to "Google Drive yetkilendirmesi erişim token'ı döndürmedi",
        "Google Drive backup failed" to "Google Drive yedeklemesi başarısız",
        "Google Drive connection was canceled." to "Google Drive bağlantısı iptal edildi.",
        "Google Drive could not be disconnected" to "Google Drive bağlantısı kesilemedi",
        "Google Drive error" to "Google Drive hatası",
        "Google Drive registration details copied" to "Google Drive kayıt ayrıntıları kopyalandı",
        "Google Drive sign-in was cancelled." to "Google Drive oturum açma işlemi iptal edildi.",
        "Google Drive, OneDrive, Nextcloud, USB, or local storage through Android" to "Android üzerinden Google Drive, OneDrive, Nextcloud, USB veya yerel depolama",
        "Google returned no access token. Check that this app's package name and signing certificate are registered for its OAuth client." to "Google erişim token'ı döndürmedi. Bu uygulamanın paket adının ve imzalama sertifikasının OAuth istemcisine kayıtlı olduğunu kontrol edin.",
        "GPU rendering" to "GPU işleme",
        "GPU rendering (blur active)" to "GPU işleme (bulanıklık etkin)",
        "Guides are bright red and diagnostic-only. They are never shown unless both Developer settings and this toggle are enabled." to "Kılavuzlar parlak kırmızıdır ve yalnızca tanılama içindir. Geliştirici ayarları ve bu anahtar birlikte etkin değilse hiçbir zaman gösterilmezler.",
        "Hide attempts" to "Denemeleri gizle",
        "Hide manual model entry" to "Elle model girişini gizle",
        "Hide OCR overlay" to "OCR katmanını gizle",
        "HTTPS endpoint" to "HTTPS uç noktası",
        "Hybrid preflight counting" to "Hibrit ön kontrol sayımı",
        "Idle / no rendered frames" to "Boşta / işlenmiş kare yok",
        "Image billing" to "Görsel faturalandırması",
        "Image generation and editing models are kept separate from chat models" to "Görsel oluşturma ve düzenleme modelleri sohbet modellerinden ayrı tutulur",
        "Image generation · describe the image you want to create" to "Görsel oluşturma · oluşturmak istediğiniz görseli açıklayın",
        "Import and continue" to "İçe aktar ve devam et",
        "Import backup" to "Yedeği içe aktar",
        "Import creates separate local copies. It never replaces an existing chat and does not import API keys or OAuth sessions." to "İçe aktarma ayrı yerel kopyalar oluşturur. Mevcut bir sohbeti asla değiştirmez ve API anahtarlarını veya OAuth oturumlarını içe aktarmaz.",
        "Import failed" to "İçe aktarma başarısız",
        "Import verification passed." to "İçe aktarma doğrulaması başarılı.",
        "Import verification warning:" to "İçe aktarma doğrulama uyarısı:",
        "Import Xylune backup" to "Xylune yedeğini içe aktar",
        "Imports are non-destructive: every chat is created as a separate copy. Existing chats are never overwritten. Provider credentials are not imported, so reconnect the required provider before continuing an imported chat." to "İçe aktarma tahribatsızdır: her sohbet ayrı bir kopya olarak oluşturulur. Mevcut sohbetlerin üzerine yazılmaz. Sağlayıcı kimlik bilgileri içe aktarılmaz; içe aktarılan bir sohbete devam etmeden önce gerekli sağlayıcıyı yeniden bağlayın.",
        "Include app settings and configuration" to "Uygulama ayarlarını ve yapılandırmayı dahil et",
        "Include attachments" to "Ekleri dahil et",
        "Include custom system prompts" to "Özel sistem istemlerini dahil et",
        "Include installed Linux environments" to "Yüklü Linux ortamlarını dahil et",
        "Include reasoning, tool traces, and request metadata" to "Akıl yürütme, araç izleri ve istek meta verilerini dahil et",
        "Included content" to "Dahil edilen içerik",
        "Included modules" to "Dahil edilen modüller",
        "Includes theme, UI behavior, new-chat defaults, provider endpoints/models, projects, prompt profiles, and automation settings. Credentials, OAuth sessions, provider authorization headers, cloud grants, drafts, and navigation state stay excluded." to "Tema, arayüz davranışı, yeni sohbet varsayılanları, sağlayıcı uç noktaları/modelleri, projeler, istem profilleri ve otomasyon ayarlarını içerir. Kimlik bilgileri, OAuth oturumları, sağlayıcı yetkilendirme başlıkları, bulut izinleri, taslaklar ve gezinme durumu hariç tutulur.",
        "Input handling" to "Girdi işleme",
        "Input tokens" to "Girdi token'ları",
        "Install a Linux workspace before enabling" to "Etkinleştirmeden önce bir Linux çalışma alanı yükleyin",
        "Install blocked" to "Yükleme engellendi",
        "Install failed" to "Yükleme başarısız",
        "Install packages" to "Paketleri yükle",
        "Install Ubuntu, Debian, or Alpine before Xylune can use Linux tools." to "Xylune Linux araçlarını kullanmadan önce Ubuntu, Debian veya Alpine yükleyin.",
        "Installation and import verification completed." to "Yükleme ve içe aktarma doğrulaması tamamlandı.",
        "Installation completed successfully." to "Yükleme başarıyla tamamlandı.",
        "Installation failed" to "Yükleme başarısız",
        "Installation failed. No success was recorded." to "Yükleme başarısız. Başarılı sonuç kaydedilmedi.",
        "Installation or import verification failed." to "Yükleme veya içe aktarma doğrulaması başarısız.",
        "Installation started" to "Yükleme başladı",
        "Installed Linux environments" to "Yüklü Linux ortamları",
        "Installed, but import verification found a problem" to "Yüklendi ancak içe aktarma doğrulaması bir sorun buldu",
        "Installing approved changes…" to "Onaylanan değişiklikler yükleniyor…",
        "Installing…" to "Yükleniyor…",
        "Interrupted response" to "Kesintiye uğrayan yanıt",
        "Its encrypted OAuth session and models will be disconnected. Chats and usage history are kept." to "Şifreli OAuth oturumu ve modellerin bağlantısı kesilir. Sohbetler ve kullanım geçmişi korunur.",
        "Its saved API key will be erased and it will disappear from model selectors. Chats and usage history are kept." to "Kaydedilmiş API anahtarı silinir ve sağlayıcı model seçicilerden kaybolur. Sohbetler ve kullanım geçmişi korunur.",
        "Keep in background" to "Arka planda tut",
        "Keep the partial answer" to "Kısmi yanıtı koru",
        "Keep Xylune open" to "Xylune'u açık tut",
        "Known calculated cost" to "Bilinen hesaplanmış maliyet",
        "Last request/answer pairs" to "Son istek/yanıt çiftleri",
        "Layout / measure" to "Yerleşim / ölçüm",
        "License catalog unavailable" to "Lisans kataloğu kullanılamıyor",
        "Linux command" to "Linux komutu",
        "Linux execution" to "Linux çalıştırma",
        "Linux package request" to "Linux paket isteği",
        "Linux terminal" to "Linux terminali",
        "Linux workspace" to "Linux çalışma alanı",
        "Linux workspace not installed" to "Linux çalışma alanı yüklü değil",
        "Linux workspace not ready" to "Linux çalışma alanı hazır değil",
        "Linux · Not installed" to "Linux · Yüklü değil",
        "Live output updates as the process prints." to "Süreç çıktı verdikçe canlı çıktı güncellenir.",
        "Live previews" to "Canlı önizlemeler",
        "Loading preview…" to "Önizleme yükleniyor…",
        "Loading usage…" to "Kullanım yükleniyor…",
        "Local Code Execution" to "Yerel Kod Çalıştırma",
        "Local code execution" to "Yerel kod çalıştırma",
        "Local description" to "Yerel açıklama",
        "Local execution starts off; enable Python or Linux only when a chat needs it." to "Yerel çalıştırma kapalı başlar; Python veya Linux'u yalnızca bir sohbet gerektiğinde etkinleştirin.",
        "Local image description" to "Yerel görsel açıklaması",
        "Local server" to "Yerel sunucu",
        "Manage Linux workspace" to "Linux çalışma alanını yönet",
        "Maximum supported reasoning" to "Desteklenen maksimum akıl yürütme",
        "Message actions" to "Mesaj işlemleri",
        "Message Xylune…" to "Xylune'a mesaj yaz…",
        "Messages, code, and reasoning are searched locally as you type." to "Yazdıkça mesajlar, kod ve akıl yürütme yerel olarak aranır.",
        "Mixed / unattributed frame work" to "Karma / kaynağı belirlenemeyen kare işi",
        "Model capabilities and request transport are selected automatically by this provider preset." to "Model yetenekleri ve istek aktarımı bu sağlayıcı ön ayarı tarafından otomatik seçilir.",
        "Model provider" to "Model sağlayıcısı",
        "Model receives OCR fallback • original preview is unchanged" to "Model OCR yedeğini alır • özgün önizleme değişmez",
        "Model refresh failed" to "Model yenileme başarısız",
        "Model review is advisory and can be wrong. Xylune records the selected model's allow/deny reason, but this is not malware analysis or a security guarantee." to "Model incelemesi yalnızca tavsiye niteliğindedir ve yanlış olabilir. Xylune seçili modelin izin/verme nedenini kaydeder; bu bir kötü amaçlı yazılım analizi veya güvenlik garantisi değildir.",
        "Models discovered for this ChatGPT account only." to "Yalnızca bu ChatGPT hesabı için bulunan modeller.",
        "More thorough reasoning" to "Daha kapsamlı akıl yürütme",
        "My DeepSeek account" to "DeepSeek hesabım",
        "Native Android BYOK model workspace." to "Yerel Android BYOK model çalışma alanı.",
        "Native compatibility warning:" to "Yerel uyumluluk uyarısı:",
        "Next branch" to "Sonraki dal",
        "Next extracted-text page" to "Sonraki çıkarılan metin sayfası",
        "Next page" to "Sonraki sayfa",
        "Next text page" to "Sonraki metin sayfası",
        "Nextcloud / WebDAV" to "Nextcloud / WebDAV",
        "No additional diagnostic text was returned by the provider." to "Sağlayıcı ek tanılama metni döndürmedi.",
        "No backup file selected." to "Yedek dosyası seçilmedi.",
        "No chat workspace is available" to "Kullanılabilir sohbet çalışma alanı yok",
        "No context was compressed" to "Hiçbir bağlam sıkıştırılmadı",
        "No conversation" to "Sohbet yok",
        "No inline preview for this file type" to "Bu dosya türü için satır içi önizleme yok",
        "No matches" to "Eşleşme yok",
        "No matching chat models" to "Eşleşen sohbet modeli yok",
        "No matching components" to "Eşleşen bileşen yok",
        "No matching image models" to "Eşleşen görsel modeli yok",
        "No output." to "Çıktı yok.",
        "No package transaction running." to "Çalışan paket işlemi yok.",
        "No password: backup remains readable to anyone who gets the file. This is allowed; choose a trusted destination." to "Parola yok: dosyayı alan herkes yedeği okuyabilir. Buna izin verilir; güvenilir bir hedef seçin.",
        "No password: the recipient can open the file immediately. This is allowed, but anyone with the file can read the included content." to "Parola yok: alıcı dosyayı hemen açabilir. Buna izin verilir; ancak dosyaya sahip olan herkes içerdiği verileri okuyabilir.",
        "No per-call usage rows were recorded for this response. The aggregate values above are still available." to "Bu yanıt için çağrı bazında kullanım satırı kaydedilmedi. Yukarıdaki toplam değerler yine kullanılabilir.",
        "No result details" to "Sonuç ayrıntısı yok",
        "No search results were returned." to "Arama sonucu döndürülmedi.",
        "Non-cached input" to "Önbelleğe alınmamış girdi",
        "Not connected yet" to "Henüz bağlı değil",
        "Not embedded" to "Gömülü değil",
        "not found" to "bulunamadı",
        "OCR fallback enabled" to "OCR yedeği etkin",
        "OCR on" to "OCR açık",
        "OCR on send" to "Gönderimde OCR",
        "OCR ready" to "OCR hazır",
        "Offline dependency catalog and full license texts" to "Çevrimdışı bağımlılık kataloğu ve tam lisans metinleri",
        "One package requirement per line. Xylune resolves Android-compatible Python 3.12 wheels before applying your approval policy." to "Satır başına bir paket gereksinimi. Xylune onay politikanızı uygulamadan önce Android uyumlu Python 3.12 wheel paketlerini çözümler.",
        "One-tap native OAuth. Xylune opens the system browser, receives the localhost callback itself, encrypts the session on this device, and refreshes it automatically. No extension or local proxy is required." to "Tek dokunuşla yerel OAuth. Xylune sistem tarayıcısını açar, localhost geri çağrısını kendisi alır, oturumu bu cihazda şifreler ve otomatik yeniler. Eklenti veya yerel proxy gerekmez.",
        "OneDrive Apps/Xylune" to "OneDrive Apps/Xylune",
        "Only missing or outdated packages will be changed. Packages and install scripts run with Xylune's app permissions." to "Yalnızca eksik veya eski paketler değiştirilir. Paketler ve kurulum betikleri Xylune'un uygulama izinleriyle çalışır.",
        "Only missing or outdated packages will change. Install scripts run with Xylune's app permissions." to "Yalnızca eksik veya eski paketler değişir. Kurulum betikleri Xylune'un uygulama izinleriyle çalışır.",
        "Only this page is held in memory. Save or share the file for full-file processing." to "Yalnızca bu sayfa bellekte tutulur. Dosyanın tamamını işlemek için kaydedin veya paylaşın.",
        "Open conversations" to "Sohbetleri aç",
        "Open full-screen preview" to "Tam ekran önizlemeyi aç",
        "Open navigation drawer" to "Gezinme çekmecesini aç",
        "Open OCR view" to "OCR görünümünü aç",
        "Output tokens" to "Çıktı token'ları",
        "Package changes" to "Paket değişiklikleri",
        "Package installation" to "Paket yükleme",
        "Package manager" to "Paket yöneticisi",
        "Package review" to "Paket incelemesi",
        "Password" to "Parola",
        "Password (optional)" to "Parola (isteğe bağlı)",
        "Pause" to "Duraklat",
        "Paused" to "Duraklatıldı",
        "Preview" to "Önizleme",
        "Previous branch" to "Önceki dal",
        "Previous page" to "Önceki sayfa",
        "Provider credentials" to "Sağlayıcı kimlik bilgileri",
        "Provider settings" to "Sağlayıcı ayarları",
        "Python execution" to "Python çalıştırma",
        "Python package request" to "Python paket isteği",
        "Reasoning" to "Akıl yürütme",
        "Reasoning details" to "Akıl yürütma ayrıntıları",
        "Reconnect" to "Yeniden bağlan",
        "Remove provider?" to "Sağlayıcı kaldırılsın mı?",
        "Repair" to "Onar",
        "Repair failed" to "Onarım başarısız",
        "Restore complete" to "Geri yükleme tamamlandı",
        "Restore failed" to "Geri yükleme başarısız",
        "Restore preview" to "Geri yükleme önizlemesi",
        "Run" to "Çalıştır",
        "Run Python" to "Python çalıştır",
        "Safe mode" to "Güvenli mod",
        "Search results" to "Arama sonuçları",
        "Send" to "Gönder",
        "Sending…" to "Gönderiliyor…",
        "Server folder" to "Sunucu klasörü",
        "Setup details" to "Kurulum ayrıntıları",
        "Show attempts" to "Denemeleri göster",
        "Show OCR overlay" to "OCR katmanını göster",
        "Source" to "Kaynak",
        "System prompt" to "Sistem istemi",
        "Try again" to "Tekrar dene",
        "Usage details" to "Kullanım ayrıntıları",
        "Verify" to "Doğrula",
        "Web page" to "Web sayfası",
        "Workspace" to "Çalışma alanı",
    )

    fun translate(text: String): String {
        exact[text]?.let { return it }

        Regex("""Connect (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} bağlantısını kur" }
        Regex("""Connected (.+) • (\d+) models available""").matchEntire(text)?.let {
            return "${it.groupValues[1]} bağlandı • ${it.groupValues[2]} model kullanılabilir"
        }
        Regex("""Connected to (.+), but no Xylune backups were found\.""").matchEntire(text)?.let {
            return "${it.groupValues[1]} bağlantısı kuruldu ancak Xylune yedeği bulunamadı."
        }
        Regex("""Could not open (.+) sign-in""").matchEntire(text)?.let { return "${it.groupValues[1]} oturum açma sayfası açılamadı" }
        Regex("""Could not read (.+) backups""").matchEntire(text)?.let { return "${it.groupValues[1]} yedekleri okunamadı" }
        Regex("""Could not send: (.+)""").matchEntire(text)?.let { return "Gönderilemedi: ${it.groupValues[1]}" }
        Regex("""Could not compile this (.+) after (\d+) repair attempts\.""").matchEntire(text)?.let {
            return "Bu ${it.groupValues[1]}, ${it.groupValues[2]} onarım denemesinden sonra derlenemedi."
        }
        Regex("""Describe what to create, or add up to (\d+) reference images to edit\.""").matchEntire(text)?.let {
            return "Oluşturmak istediğinizi açıklayın veya düzenlemek için en fazla ${it.groupValues[1]} referans görsel ekleyin."
        }
        Regex("""Image requests cannot include ordinary files\. Remove the non-image attachments?""").matchEntire(text)?.let {
            return "Görsel istekleri normal dosya içeremez. Görsel olmayan ekleri kaldırın."
        }
        Regex("""Found (\d+) Xylune backups?""").matchEntire(text)?.let { return "${it.groupValues[1]} Xylune yedeği bulundu" }
        Regex("""Installed (.+)""").matchEntire(text)?.let { return "Yüklendi: ${it.groupValues[1]}" }
        Regex("""Installed and import-verified:? (.+)""").matchEntire(text)?.let { return "Yüklendi ve içe aktarma doğrulandı: ${it.groupValues[1]}" }
        Regex("""Downloading (.+)…""").matchEntire(text)?.let { return "${it.groupValues[1]} indiriliyor…" }
        Regex("""Installation blocked • (.+)""").matchEntire(text)?.let { return "Yükleme engellendi • ${it.groupValues[1]}" }
        Regex("""Installation denied • (.+)""").matchEntire(text)?.let { return "Yükleme reddedildi • ${it.groupValues[1]}" }
        Regex("""Linux data on disk: (.+)""").matchEntire(text)?.let { return "Diskteki Linux verisi: ${it.groupValues[1]}" }
        Regex("""OCR could not read (.+); the original file is still attached""").matchEntire(text)?.let {
            return "OCR ${it.groupValues[1]} dosyasını okuyamadı; özgün dosya hâlâ ekli"
        }
        Regex("""OCR fallback is ready for (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} için OCR yedeği hazır" }
        Regex("""Environment (.+)""").matchEntire(text)?.let { return "Ortam ${it.groupValues[1]}" }
        Regex("""Exit (\d+)""").matchEntire(text)?.let { return "Çıkış ${it.groupValues[1]}" }
        Regex("""Elapsed (.+)""").matchEntire(text)?.let { return "Geçen süre ${it.groupValues[1]}" }
        Regex("""in (\d+)d""").matchEntire(text)?.let { return "${it.groupValues[1]} gün sonra" }
        Regex("""in (\d+)h""").matchEntire(text)?.let { return "${it.groupValues[1]} saat sonra" }
        Regex("""in (\d+)m""").matchEntire(text)?.let { return "${it.groupValues[1]} dakika sonra" }
        Regex("""in (\d+)s""").matchEntire(text)?.let { return "${it.groupValues[1]} saniye sonra" }
        Regex("""in (\d+)d (\d+)h""").matchEntire(text)?.let { return "${it.groupValues[1]} gün ${it.groupValues[2]} saat sonra" }
        Regex("""in (\d+)h (\d+)m""").matchEntire(text)?.let { return "${it.groupValues[1]} saat ${it.groupValues[2]} dakika sonra" }
        Regex("""in (\d+)m (\d+)s""").matchEntire(text)?.let { return "${it.groupValues[1]} dakika ${it.groupValues[2]} saniye sonra" }
        Regex("""Open (.+) terminal""").matchEntire(text)?.let { return "${it.groupValues[1]} terminalini aç" }
        Regex("""Install (.+) packages""").matchEntire(text)?.let { return "${it.groupValues[1]} paketlerini yükle" }
        Regex("""Install (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} yükle" }
        Regex("""Delete (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} sil" }
        Regex("""Edit (.+)""").matchEntire(text)?.let { return "${it.groupValues[1]} düzenle" }
        Regex("""Downloaded: (.+)""").matchEntire(text)?.let { return "İndirildi: ${it.groupValues[1]}" }
        Regex("""Download: (.+)""").matchEntire(text)?.let { return "İndirme: ${it.groupValues[1]}" }
        Regex("""Disk: (.+)""").matchEntire(text)?.let { return "Disk: ${it.groupValues[1]}" }
        return text
    }
}
