package app.xylune.chat.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import app.xylune.chat.settings.AppLanguage
import java.util.Locale

internal enum class XyluneUiLanguage { ENGLISH, TURKISH }

internal val LocalXyluneUiLanguage = compositionLocalOf { XyluneUiLanguage.ENGLISH }

internal fun resolvedUiLanguage(preference: AppLanguage, systemLanguage: String = Locale.getDefault().language): XyluneUiLanguage =
    when (preference) {
        AppLanguage.TURKISH -> XyluneUiLanguage.TURKISH
        AppLanguage.ENGLISH -> XyluneUiLanguage.ENGLISH
        AppLanguage.SYSTEM -> if (systemLanguage.equals("tr", ignoreCase = true)) XyluneUiLanguage.TURKISH else XyluneUiLanguage.ENGLISH
    }

@Composable
internal fun uiText(value: String): String = localizeUiText(value, LocalXyluneUiLanguage.current)

internal fun localizeUiText(value: String, language: XyluneUiLanguage): String {
    if (language != XyluneUiLanguage.TURKISH || value.isBlank()) return value
    val first = value.indexOfFirst { !it.isWhitespace() }
    if (first < 0) return value
    val last = value.indexOfLast { !it.isWhitespace() }
    val prefix = value.substring(0, first)
    val core = value.substring(first, last + 1)
    val suffix = value.substring(last + 1)
    val translated = TURKISH_UI_STRINGS[core] ?: localizeTurkishDynamic(core)
    return prefix + translated + suffix
}

private fun localizeTurkishDynamic(value: String): String {
    val rules = listOf<(String) -> String?>(
        { text -> Regex("^Continue from step (\\d+) of 3$").matchEntire(text)?.let { "3 adımın ${it.groupValues[1]}. adımından devam et" } },
        { text -> Regex("^(\\d+) providers? configured$").matchEntire(text)?.let { "${it.groupValues[1]} sağlayıcı yapılandırıldı" } },
        { text -> Regex("^(\\d+) selected$").matchEntire(text)?.let { "${it.groupValues[1]} seçildi" } },
        { text -> Regex("^(\\d+) starred$").matchEntire(text)?.let { "${it.groupValues[1]} yıldızlı" } },
        { text -> Regex("^(\\d+) of (\\d+) selected$").matchEntire(text)?.let { "${it.groupValues[2]} öğeden ${it.groupValues[1]} tanesi seçildi" } },
        { text -> Regex("^Search (\\d+) models$").matchEntire(text)?.let { "${it.groupValues[1]} modelde ara" } },
        { text -> Regex("^(\\d+) available for (.+) · metadata refreshes with the catalog$").matchEntire(text)?.let { "${it.groupValues[2]} için ${it.groupValues[1]} model kullanılabilir · meta veriler katalogla yenilenir" } },
        { text -> Regex("^Page (\\d+) of (\\d+)$").matchEntire(text)?.let { "Sayfa ${it.groupValues[1]} / ${it.groupValues[2]}" } },
        { text -> Regex("^Source (\\d+)$").matchEntire(text)?.let { "Kaynak ${it.groupValues[1]}" } },
        { text -> Regex("^(.+) connection$").matchEntire(text)?.let { "${it.groupValues[1]} bağlantısı" } },
        { text -> Regex("^(.+) models$").matchEntire(text)?.let { "${it.groupValues[1]} modelleri" } },
        { text -> Regex("^Connect (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} bağla" } },
        { text -> Regex("^Configure (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} yapılandır" } },
        { text -> Regex("^Waiting for (.+) authorization…$").matchEntire(text)?.let { "${it.groupValues[1]} yetkilendirmesi bekleniyor…" } },
        { text -> Regex("^Remove (.+)\\?$").matchEntire(text)?.let { "${it.groupValues[1]} kaldırılsın mı?" } },
        { text -> Regex("^Install (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} yükle" } },
        { text -> Regex("^Open (.+) terminal$").matchEntire(text)?.let { "${it.groupValues[1]} terminalini aç" } },
        { text -> Regex("^Install (.+) packages$").matchEntire(text)?.let { "${it.groupValues[1]} paketlerini yükle" } },
        { text -> Regex("^(\\d+) packages resolved • (\\d+) changes(?: • (\\d+) dependencies)?$").matchEntire(text)?.let { m ->
            buildString { append("${m.groupValues[1]} paket çözümlendi • ${m.groupValues[2]} değişiklik"); m.groupValues.getOrNull(3)?.takeIf(String::isNotBlank)?.let { append(" • $it bağımlılık") } }
        } },
        { text -> Regex("^Download: (.+)$").matchEntire(text)?.let { "İndirme: ${it.groupValues[1]}" } },
        { text -> Regex("^Disk: (.+)$").matchEntire(text)?.let { "Disk: ${it.groupValues[1]}" } },
        { text -> Regex("^Environment (.+)$").matchEntire(text)?.let { "Ortam ${it.groupValues[1]}" } },
        { text -> Regex("^Python (.+) • (.+) packages • (.+)$").matchEntire(text)?.let { "Python ${it.groupValues[1]} • ${it.groupValues[2]} paket • ${it.groupValues[3]}" } },
        { text -> Regex("^exit (\\d+) • (.+) ms$").matchEntire(text)?.let { "çıkış ${it.groupValues[1]} • ${it.groupValues[2]} ms" } },
        { text -> Regex("^Xylune (.+) is available$").matchEntire(text)?.let { "Xylune ${it.groupValues[1]} kullanılabilir" } },
        { text -> Regex("^Xylune (.+) is available from (.+)$").matchEntire(text)?.let { "Xylune ${it.groupValues[1]} ${it.groupValues[2]} üzerinden kullanılabilir" } },
        { text -> Regex("^Delete (\\d+) memories\\?$").matchEntire(text)?.let { "${it.groupValues[1]} bellek silinsin mi?" } },
        { text -> Regex("^(.+) will be permanently removed from its cloud provider\\.$").matchEntire(text)?.let { "${it.groupValues[1]} bulut sağlayıcısından kalıcı olarak kaldırılacak." } },
        { text -> Regex("^(.+) will be permanently deleted from (.+)\\.$").matchEntire(text)?.let { "${it.groupValues[1]} ${it.groupValues[2]} üzerinden kalıcı olarak silinecek." } },
        { text -> Regex("^Preset: (.+)$").matchEntire(text)?.let { "Ön ayar: ${it.groupValues[1]}" } },
        { text -> Regex("^(.+) credential$").matchEntire(text)?.let { "${it.groupValues[1]} kimlik bilgisi" } },
        { text -> Regex("^(.+) installed$").matchEntire(text)?.let { "${it.groupValues[1]} yüklü" } },
        { text -> Regex("^(.+) install failed$").matchEntire(text)?.let { "${it.groupValues[1]} kurulumu başarısız" } },
        { text -> Regex("^Preview unavailable: (.+)$").matchEntire(text)?.let { "Önizleme kullanılamıyor: ${it.groupValues[1]}" } },
        { text -> Regex("^PDF preview unavailable: (.+)$").matchEntire(text)?.let { "PDF önizlemesi kullanılamıyor: ${it.groupValues[1]}" } },
        { text -> Regex("^Edit (.+) source$").matchEntire(text)?.let { "${it.groupValues[1]} kaynağını düzenle" } },
        { text -> Regex("""^Attempt (\d+) · repeated candidate · (\d+) error\(s\)$""").matchEntire(text)?.let { "Deneme ${it.groupValues[1]} · yinelenen aday · ${it.groupValues[2]} hata" } },
        { text -> Regex("""^Attempt (\d+) · (\d+) error\(s\)$""").matchEntire(text)?.let { "Deneme ${it.groupValues[1]} · ${it.groupValues[2]} hata" } },
        { text -> Regex("^Attempt (\\d+) · (.+)$").matchEntire(text)?.let { "Deneme ${it.groupValues[1]} · ${it.groupValues[2]}" } },
        { text -> Regex("^(\\d+) error\\(s\\)$").matchEntire(text)?.let { "${it.groupValues[1]} hata" } },
        { text -> Regex("^(.+) ready$").matchEntire(text)?.let { "${it.groupValues[1]} hazır" } },
        { text -> Regex("^Configured as (.+) • tap to check backups$").matchEntire(text)?.let { "${it.groupValues[1]} olarak yapılandırıldı • yedekleri denetlemek için dokunun" } },
        { text -> Regex("""^Allow (\d+) listed network origins\?$""").matchEntire(text)?.let { "${it.groupValues[1]} listelenen ağ kaynağına izin ver" } },
        { text -> Regex("^Delete (\\d+) disabled memories\\?$").matchEntire(text)?.let { "${it.groupValues[1]} devre dışı bellek silinsin mi?" } },
        { text -> Regex("^Delete (\\d+) disabled memory\\?$").matchEntire(text)?.let { "${it.groupValues[1]} devre dışı bellek silinsin mi?" } },
        { text -> Regex("""^Updates are checked against (.+)\.$""").matchEntire(text)?.let { "Güncellemeler ${it.groupValues[1]} ile karşılaştırılarak denetlenir." } },
        { text -> Regex("^Checking (.+)…$").matchEntire(text)?.let { "${it.groupValues[1]} denetleniyor…" } },
    )
    val extraRules = listOf<(String) -> String?>(
        { text -> Regex("^Chat · (\\d+)$").matchEntire(text)?.let { "Sohbet · ${it.groupValues[1]}" } },
        { text -> Regex("^Images · (\\d+)$").matchEntire(text)?.let { "Görseller · ${it.groupValues[1]}" } },
        { text -> Regex("^(\\d+) providers? ready$").matchEntire(text)?.let { "${it.groupValues[1]} sağlayıcı hazır" } },
        { text -> Regex("^(.+) paused for crash recovery$").matchEntire(text)?.let { m -> "${TURKISH_UI_STRINGS[m.groupValues[1]] ?: m.groupValues[1]} çökme kurtarması için duraklatıldı" } },
        { text -> Regex("^Managed by Xylune · revision (.+)$").matchEntire(text)?.let { "Xylune tarafından yönetiliyor · revizyon ${it.groupValues[1]}" } },
        { text -> Regex("^Protocol: (.+)$").matchEntire(text)?.let { "Protokol: ${it.groupValues[1]}" } },
        { text -> Regex("^Build variable: (.+)$").matchEntire(text)?.let { "Derleme değişkeni: ${it.groupValues[1]}" } },
        { text -> Regex("^Redirect URI: (.+)$").matchEntire(text)?.let { "Yönlendirme URI'si: ${it.groupValues[1]}" } },
        { text -> Regex("^(.+) simulates the complete transaction first and checks what is already installed before approval\\.$").matchEntire(text)?.let { "${it.groupValues[1]} önce işlemin tamamını simüle eder ve onaydan önce zaten yüklü olanları kontrol eder." } },
        { text -> Regex("^Allow (.+) package changes\\?$").matchEntire(text)?.let { "${it.groupValues[1]} paket değişikliklerine izin verilsin mi?" } },
        { text -> Regex("^This is the complete (.+) simulation, including dependencies:$").matchEntire(text)?.let { "Bu, bağımlılıklar dahil tam ${it.groupValues[1]} simülasyonudur:" } },
        { text -> Regex("^(.+) will remove this Python package from the current chat environment\\. Other packages and the optional Linux runtime are kept\\.$").matchEntire(text)?.let { "${it.groupValues[1]} bu Python paketini mevcut sohbet ortamından kaldıracak. Diğer paketler ve isteğe bağlı Linux çalışma zamanı korunur." } },
        { text -> Regex("^This has taken (\\d+) seconds\\. It will keep running while you browse Xylune, up to its hard deadline\\. You can leave it in the background or stop it now\\. A blocking native Python extension may take a moment to return after Stop\\.$").matchEntire(text)?.let { "Bu işlem ${it.groupValues[1]} saniyedir sürüyor. Kesin süre sınırına kadar Xylune'da gezinirken çalışmaya devam edecek. Arka planda bırakabilir veya şimdi durdurabilirsiniz. Engelleyen yerel bir Python eklentisinin Durdur'dan sonra dönmesi biraz zaman alabilir." } },
        { text -> Regex("^Edit (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} öğesini düzenle" } },
        { text -> Regex("^Delete (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} öğesini sil" } },
        { text -> Regex("^Remove (.+)$").matchEntire(text)?.let { "${it.groupValues[1]} öğesini kaldır" } },
        { text -> Regex("^(.+) · (prepend|override)$", RegexOption.IGNORE_CASE).matchEntire(text)?.let { m ->
            val mode = if (m.groupValues[2].equals("prepend", true)) "Başa ekle" else "Geçersiz kıl"
            "${m.groupValues[1]} · $mode"
        } },
        { text -> Regex("^(.+) • (.+) • (.+)$").matchEntire(text)?.let { m ->
            val first = TURKISH_UI_STRINGS[m.groupValues[1]] ?: m.groupValues[1]
            val second = TURKISH_UI_STRINGS[m.groupValues[2]] ?: m.groupValues[2]
            val third = TURKISH_UI_STRINGS[m.groupValues[3]] ?: m.groupValues[3]
            if (first == m.groupValues[1] && second == m.groupValues[2] && third == m.groupValues[3]) null else "$first • $second • $third"
        } },
    )
    rules.forEach { rule -> rule(value)?.let { return it } }
    extraRules.forEach { rule -> rule(value)?.let { return it } }
    return value
}

private val TURKISH_UI_STRINGS = mapOf(
    "Dynamic" to "Dinamik",
    "Graphite" to "Grafit",
    "Ocean" to "Okyanus",
    "Violet" to "Menekşe",
    "Sunset" to "Gün batımı",
    "Xylune's natural green Material palette" to "Xylune'un doğal yeşil Material paleti",
    "Colors generated from your wallpaper on Android 12+" to "Android 12+ üzerinde duvar kâğıdınızdan oluşturulan renkler",
    "Restrained blue-gray palette" to "Dengeli mavi-gri palet",
    "Cool teal and cyan accents" to "Soğuk turkuaz ve camgöbeği vurgular",
    "Deep purple with soft rose accents" to "Yumuşak gül vurgulu koyu mor",
    "Warm orange, rose, and gold accents" to "Sıcak turuncu, gül ve altın vurgular",
    "Top left" to "Sol üst",
    "Top right" to "Sağ üst",
    "Bottom left" to "Sol alt",
    "Bottom right" to "Sağ alt",
    "Minimal" to "Minimum",
    "Medium" to "Orta",
    "Extra high" to "Çok yüksek",
    "Expanded" to "Genişletilmiş",
    "While working" to "Çalışırken",
    "Collapsed" to "Daraltılmış",
    "Native only" to "Yalnızca yerel",
    "Installed" to "Yüklü",
    "Not installed" to "Kurulu değil",
    "Downloading" to "İndiriliyor",
    "Verifying" to "Doğrulanıyor",
    "Extracting" to "Çıkarılıyor",
    "Configuring" to "Yapılandırılıyor",
    "Ready" to "Hazır",
    "Error" to "Hata",
    "Unsupported" to "Desteklenmiyor",
    "Advanced limits and prompt behavior for this conversation. Thinking, effort, tools, files, and Deep Research live beside the message box." to "Bu sohbet için gelişmiş sınırlar ve istem davranışı. Düşünme, düzey, araçlar, dosyalar ve Derin Araştırma mesaj kutusunun yanında bulunur.",
    "Android grants Xylune persistent access only to the folder you select. Create or choose a dedicated Xylune folder; no account-wide permission is requested." to "Android, Xylune'a yalnızca seçtiğiniz klasöre kalıcı erişim verir. Xylune'a ayrılmış bir klasör oluşturun veya seçin; hesap genelinde izin istenmez.",
    "Android themed icons can recolor Xylune's monochrome layer. Dynamic uses the live wallpaper-derived Material You palette when themed icons are off." to "Android temalı simgeleri Xylune'un tek renkli katmanını yeniden renklendirebilir. Dinamik seçenek, temalı simgeler kapalıyken duvar kâğıdından türetilen canlı Material You paletini kullanır.",
    "API keys are stored in Android encrypted preferences. Native-only mode never silently switches to a Xylune engine; Automatic mode does." to "API anahtarları Android şifreli tercihlerinde saklanır. Yalnızca yerel mod hiçbir zaman sessizce bir Xylune motoruna geçmez; Otomatik mod gerektiğinde geçer.",
    "Attributes slow frames to Android frame stages, Xylune blur work, Compose recomposition pressure, allocations, and blocking GC. It adds some diagnostic overhead, so use it while reproducing an issue." to "Yavaş kareleri Android kare aşamalarına, Xylune bulanıklık işlemlerine, Compose yeniden oluşturma baskısına, bellek ayırmalarına ve engelleyen GC'ye bağlar. Bir miktar tanılama yükü ekler; bu nedenle sorunu yeniden üretirken kullanın.",
    "Chats, branches, app configuration, organization, metadata, and optional attachments. API keys and OAuth sessions are deliberately excluded." to "Sohbetler, dallar, uygulama yapılandırması, düzen, meta veriler ve isteğe bağlı ekler. API anahtarları ve OAuth oturumları özellikle hariç tutulur.",
    "Chats, credentials, and workspaces stay on your device. Xylune connects directly to providers you configure and has no application backend, ads, or telemetry." to "Sohbetler, kimlik bilgileri ve çalışma alanları cihazınızda kalır. Xylune yapılandırdığınız sağlayıcılara doğrudan bağlanır; uygulama arka ucu, reklamları veya telemetrisi yoktur.",
    "Choose where Xylune should look. Every option is limited to app-only storage or a folder you explicitly select." to "Xylune'un nereye bakacağını seçin. Her seçenek yalnızca uygulamaya özel depolamayla veya açıkça seçtiğiniz bir klasörle sınırlıdır.",
    "Credentials were found and this step is complete." to "Kimlik bilgileri bulundu ve bu adım tamamlandı.",
    "Development disclosure & disclaimer" to "Geliştirme açıklaması ve sorumluluk reddi",
    "Direct app storage" to "Doğrudan uygulama depolaması",
    "Distribution selection, installation, packages, and removal are managed in one place." to "Dağıtım seçimi, kurulum, paketler ve kaldırma tek bir yerden yönetilir.",
    "Enabled by default. Technical symbols and emoji requested by the user are not blocked." to "Varsayılan olarak etkindir. Teknik semboller ve kullanıcının istediği emojiler engellenmez.",
    "Enter Xylune now. You can return to Providers & models from Settings at any time." to "Şimdi Xylune'a girin. Ayarlar'dan istediğiniz zaman Sağlayıcılar ve modeller bölümüne dönebilirsiniz.",
    "Every grant belongs only to this pinned copy. Network access is limited to the listed HTTPS origins, and folder access cannot leave the selected document tree." to "Her izin yalnızca bu sabitlenmiş kopyaya aittir. Ağ erişimi listelenen HTTPS kaynaklarıyla sınırlıdır ve klasör erişimi seçilen belge ağacının dışına çıkamaz.",
    "Everything listed here is embedded in this build and available without a network connection." to "Burada listelenen her şey bu derlemeye gömülüdür ve ağ bağlantısı olmadan kullanılabilir.",
    "Exact provider counters where available, then local family and generic fallbacks." to "Mümkün olduğunda sağlayıcının kesin sayaçları, ardından yerel model ailesi ve genel yedek tahminler kullanılır.",
    "GitHub release workflows embed their own owner/repository. Fork builds therefore follow the fork they came from." to "GitHub sürüm iş akışları kendi sahip/depo bilgisini gömer. Bu nedenle fork derlemeleri geldikleri fork'u izler.",
    "Guides are bright red and diagnostic-only. They are never shown unless both Developer settings and this toggle are enabled." to "Kılavuzlar parlak kırmızıdır ve yalnızca tanılama amaçlıdır. Hem Geliştirici ayarları hem de bu anahtar etkin değilse asla gösterilmezler.",
    "Imports are non-destructive: every chat is created as a separate copy. Existing chats are never overwritten. Provider credentials are not imported, so reconnect the required provider before continuing an imported chat." to "İçe aktarma zarar vermez: her sohbet ayrı bir kopya olarak oluşturulur. Mevcut sohbetlerin üzerine asla yazılmaz. Sağlayıcı kimlik bilgileri içe aktarılmaz; içe aktarılan bir sohbete devam etmeden önce gerekli sağlayıcıyı yeniden bağlayın.",
    "Includes theme, UI behavior, new-chat defaults, provider endpoints/models, projects, prompt profiles, and automation settings. Credentials, OAuth sessions, provider authorization headers, cloud grants, drafts, and navigation state stay excluded." to "Tema, arayüz davranışı, yeni sohbet varsayılanları, sağlayıcı uç noktaları/modelleri, projeler, istem profilleri ve otomasyon ayarlarını içerir. Kimlik bilgileri, OAuth oturumları, sağlayıcı yetkilendirme üst bilgileri, bulut izinleri, taslaklar ve gezinme durumu hariç tutulur.",
    "Install Ubuntu, Debian, or Alpine before Xylune can use Linux tools." to "Xylune Linux araçlarını kullanmadan önce Ubuntu, Debian veya Alpine kurun.",
    "Keep Xylune open" to "Xylune'u açık tut",
    "License catalog unavailable" to "Lisans kataloğu kullanılamıyor",
    "Model review is advisory and can be wrong. Xylune records the selected model's allow/deny reason, but this is not malware analysis or a security guarantee." to "Model incelemesi yalnızca bilgilendirme amaçlıdır ve hatalı olabilir. Xylune seçili modelin izin/ret nedenini kaydeder; bu bir zararlı yazılım analizi veya güvenlik garantisi değildir.",
    "No per-call usage rows were recorded for this response. The aggregate values above are still available." to "Bu yanıt için çağrı başına kullanım kaydı tutulmadı. Yukarıdaki toplam değerler yine de kullanılabilir.",
    "No Xylune account, ads, analytics, or Xylune cloud. Chat history and API keys remain on this device; traffic goes to endpoints and web tools you explicitly enable." to "Xylune hesabı, reklam, analitik veya Xylune bulutu yoktur. Sohbet geçmişi ve API anahtarları bu cihazda kalır; trafik yalnızca açıkça etkinleştirdiğiniz uç noktalara ve web araçlarına gider.",
    "Off by default. Normal chats show only a concise failure summary and Retry." to "Varsayılan olarak kapalıdır. Normal sohbetler yalnızca kısa bir hata özeti ve Yeniden dene seçeneğini gösterir.",
    "One-tap native OAuth. Xylune opens the system browser, receives the localhost callback itself, encrypts the session on this device, and refreshes it automatically. No extension or local proxy is required." to "Tek dokunuşla yerel OAuth. Xylune sistem tarayıcısını açar, localhost geri çağrısını kendisi alır, oturumu bu cihazda şifreler ve otomatik yeniler. Eklenti veya yerel proxy gerekmez.",
    "Only this page is held in memory. Save or share the file for full-file processing." to "Bellekte yalnızca bu sayfa tutulur. Dosyanın tamamını işlemek için kaydedin veya paylaşın.",
    "Opened by Xylune" to "Xylune tarafından açıldı",
    "Optional. Preview a local or cloud backup before importing anything." to "İsteğe bağlı. Herhangi bir şeyi içe aktarmadan önce yerel veya bulut yedeğini önizleyin.",
    "Packages and their installers run with Xylune's app permissions. Ubuntu is for compatibility, not containment; these settings intentionally reduce confirmation barriers." to "Paketler ve kurucuları Xylune'un uygulama izinleriyle çalışır. Ubuntu uyumluluk içindir, yalıtım için değil; bu ayarlar onay engellerini bilerek azaltır.",
    "Per-response call breakdowns are available from each assistant message's ⋮ menu." to "Yanıt başına çağrı dökümleri her asistan mesajının ⋮ menüsünden görülebilir.",
    "Portable cloud backups can include chats, app settings, organization, and optional Linux root filesystems. Passwordless backups are allowed after an explicit warning; API keys, OAuth sessions, provider authorization headers, cloud grants, and database encryption keys are excluded." to "Taşınabilir bulut yedekleri sohbetleri, uygulama ayarlarını, düzeni ve isteğe bağlı Linux kök dosya sistemlerini içerebilir. Açık bir uyarıdan sonra parolasız yedeklere izin verilir; API anahtarları, OAuth oturumları, sağlayıcı yetkilendirme üst bilgileri, bulut izinleri ve veritabanı şifreleme anahtarları hariç tutulur.",
    "Python and Linux share this chat's private /workspace. Runtime setup, packages, health, tests, and removal have one owner here." to "Python ve Linux bu sohbetin özel /workspace alanını paylaşır. Çalışma zamanı kurulumu, paketler, durum, testler ve kaldırma burada tek yerden yönetilir.",
    "Python is built in. Linux is an optional compatibility layer with a separate download. Pick a runtime only when you need to inspect or change it." to "Python yerleşiktir. Linux ayrı indirilen isteğe bağlı bir uyumluluk katmanıdır. Yalnızca incelemeniz veya değiştirmeniz gerektiğinde bir çalışma zamanı seçin.",
    "QUERY" to "SORGU",
    "Raw token totals recorded from provider calls. Use these with the provider's current pricing when you want to verify or calculate cost manually." to "Sağlayıcı çağrılarından kaydedilen ham token toplamları. Maliyeti elle doğrulamak veya hesaplamak istediğinizde bunları sağlayıcının güncel fiyatlarıyla kullanın.",
    "Reference image" to "Referans görsel",
    "Release to snap to the nearest supported level" to "En yakın desteklenen düzeye oturtmak için bırakın",
    "Restore a backup if you have one, then connect the model provider you actually want to use. Everything optional stays out of your way." to "Varsa bir yedeği geri yükleyin, ardından gerçekten kullanmak istediğiniz model sağlayıcısını bağlayın. İsteğe bağlı her şey yolunuza çıkmaz.",
    "Safe defaults share visible messages and attachments. Hidden reasoning, tool diagnostics, prompts, and request snapshots stay excluded until you enable them." to "Güvenli varsayılanlar görünür mesajları ve ekleri paylaşır. Gizli akıl yürütme, araç tanılamaları, istemler ve istek anlık görüntüleri siz etkinleştirene kadar hariç kalır.",
    "Search chats and messages" to "Sohbetlerde ve mesajlarda ara",
    "Set up Xylune" to "Xylune'u kur",
    "Source read completed" to "Kaynak okuma tamamlandı",
    "Starting fresh? Ignore the restore card and tap Continue." to "Sıfırdan mı başlıyorsunuz? Geri yükleme kartını yok sayıp Devam et'e dokunun.",
    "The app is provided “AS IS”, without warranties. Use it at your own risk. To the maximum extent permitted by applicable law, the author and contributors are not responsible for data loss, device damage, account loss, charges, security incidents, or other consequences arising from its use, modification, or distribution. Review the source and keep backups before relying on it." to "Uygulama herhangi bir garanti olmaksızın “OLDUĞU GİBİ” sunulur. Kullanım riski size aittir. Yürürlükteki hukukun izin verdiği azami ölçüde yazar ve katkıda bulunanlar; kullanım, değiştirme veya dağıtımdan kaynaklanan veri kaybı, cihaz hasarı, hesap kaybı, ücretler, güvenlik olayları veya diğer sonuçlardan sorumlu değildir. Güvenmeden önce kaynak kodunu inceleyin ve yedeklerinizi koruyun.",
    "The built-in provider catalog is delayed. Setup remains usable and Xylune will keep retrying in the background." to "Yerleşik sağlayıcı kataloğu gecikti. Kurulum kullanılabilir durumda kalır ve Xylune arka planda yeniden denemeye devam eder.",
    "The embedded license document could not be opened." to "Gömülü lisans belgesi açılamadı.",
    "The overlay explicitly shares pointer input with the content underneath and never consumes it. Taps, scrolling, drawer gestures, and back navigation continue through the panel." to "Katman işaretçi girişini alttaki içerikle açıkça paylaşır ve hiçbir zaman tüketmez. Dokunmalar, kaydırma, çekmece hareketleri ve geri gezinme panelin üzerinden çalışmaya devam eder.",
    "The Xylune maintainer does not create, train, host, pre-review, or endorse individual model outputs. AI output can be wrong, unsafe, biased, or unsuitable; verify it before relying on it. Provider terms, fees, retention, and content rules apply independently." to "Xylune geliştiricisi tek tek model çıktılarını oluşturmaz, eğitmez, barındırmaz, önceden incelemez veya onaylamaz. Yapay zekâ çıktısı yanlış, güvensiz, önyargılı veya uygunsuz olabilir; güvenmeden önce doğrulayın. Sağlayıcı koşulları, ücretleri, saklama ve içerik kuralları bağımsız olarak geçerlidir.",
    "These providers keep Xylune backups in an app-specific folder or prefix. OAuth tokens and storage credentials are encrypted on this device and excluded from exported backups." to "Bu sağlayıcılar Xylune yedeklerini uygulamaya özel bir klasör veya önekte tutar. OAuth tokenları ve depolama kimlik bilgileri bu cihazda şifrelenir ve dışa aktarılan yedeklere dahil edilmez.",
    "This attempt continued in the newer step below." to "Bu deneme aşağıdaki daha yeni adımda devam etti.",
    "This build is missing its generated offline notices." to "Bu derlemede oluşturulmuş çevrimdışı bildirimler eksik.",
    "This is a debug-signed development build." to "Bu, hata ayıklama anahtarıyla imzalanmış bir geliştirme derlemesidir.",
    "This is the compiled launcher program. Local controls run here; live HTTP data and JSON bindings were preflighted before this card appeared." to "Bu, derlenmiş başlatıcı programıdır. Yerel denetimler burada çalışır; canlı HTTP verileri ve JSON bağlamaları bu kart görünmeden önce ön kontrolden geçirilmiştir.",
    "This location is connected, but it does not contain a Xylune backup yet." to "Bu konum bağlı, ancak henüz bir Xylune yedeği içermiyor.",
    "This widget stays on-device and requests no network, location, folder, or scheduled-refresh access." to "Bu widget cihazda kalır ve ağ, konum, klasör veya zamanlanmış yenileme erişimi istemez.",
    "Token fields are stored from provider usage metadata when the provider reports them. Otherwise Xylune may fall back to its local counter/estimator. Use the raw token counts above with your provider's current pricing table for manual calculation." to "Sağlayıcı bildirdiğinde token alanları sağlayıcının kullanım meta verilerinden kaydedilir. Aksi halde Xylune yerel sayaç/tahminleyicisine başvurabilir. Elle hesaplama için yukarıdaki ham token sayılarını sağlayıcınızın güncel fiyat tablosuyla kullanın.",
    "Tools available to Xylune in this chat" to "Bu sohbette Xylune'un kullanabildiği araçlar",
    "Try a library name such as SQLCipher or a license such as Apache-2.0." to "SQLCipher gibi bir kitaplık adı veya Apache-2.0 gibi bir lisans deneyin.",
    "Use custom instruction profiles for additional tone and workflow preferences." to "Ek üslup ve iş akışı tercihleri için özel talimat profillerini kullanın.",
    "Uses only Drive's hidden appDataFolder. Connect once, then create, browse, preview, and restore backups without repeating the consent flow." to "Yalnızca Drive'ın gizli appDataFolder alanını kullanır. Bir kez bağlanın; ardından onay akışını tekrarlamadan yedek oluşturun, göz atın, önizleyin ve geri yükleyin.",
    "What are we creating?" to "Ne oluşturuyoruz?",
    "Xylune adds request-specific date, enabled-tool, research, memory, attachment, and generated-content instructions at runtime. Those dynamic layers are not editable either and are not presented as one misleading static block." to "Xylune çalışma zamanında isteğe özel tarih, etkin araç, araştırma, bellek, ek ve oluşturulan içerik talimatları ekler. Bu dinamik katmanlar da düzenlenemez ve yanıltıcı tek bir statik blok olarak sunulmaz.",
    "Xylune asks for the non-sensitive drive.appdata scope only. The backup files remain hidden from normal Drive browsing and from other apps." to "Xylune yalnızca hassas olmayan drive.appdata kapsamını ister. Yedek dosyaları normal Drive gezintisinden ve diğer uygulamalardan gizli kalır.",
    "Xylune includes each installed root filesystem, packages, and configuration. Permissions, symbolic links, and hard links are preserved. This can make the backup several gigabytes." to "Xylune her kurulu kök dosya sistemini, paketlerini ve yapılandırmasını dahil eder. İzinler, sembolik bağlantılar ve sabit bağlantılar korunur. Bu, yedeği birkaç gigabayta çıkarabilir.",
    "Xylune was made with full vibe coding: features and changes were primarily directed in natural language and implemented with AI-assisted coding tools. It may contain serious defects." to "Xylune tamamen vibe coding yaklaşımıyla geliştirildi: özellikler ve değişiklikler ağırlıklı olarak doğal dille yönlendirildi ve yapay zekâ destekli kodlama araçlarıyla uygulandı. Ciddi hatalar içerebilir.",
    "Broad compatibility and the largest package selection" to "Geniş uyumluluk ve en büyük paket seçimi",
    "Stable, compact, and compatible with Debian packages" to "Kararlı, kompakt ve Debian paketleriyle uyumlu",
    "Smallest download; uses musl and apk" to "En küçük indirme; musl ve apk kullanır",
    "Automatic" to "Otomatik",
    "Use the model provider's native server-side search when supported, otherwise use the selected Xylune search engine." to "Desteklendiğinde model sağlayıcısının yerel sunucu tarafı aramasını, aksi halde seçili Xylune arama motorunu kullanır.",
    "Provider native only" to "Yalnızca sağlayıcının yerel araması",
    "Require the selected provider/model to perform search itself. Unsupported models fail instead of silently switching engines." to "Seçili sağlayıcı/modelin aramayı kendisinin yapmasını zorunlu kılar. Desteklenmeyen modeller sessizce motor değiştirmek yerine hata verir.",
    "Xylune search engine" to "Xylune arama motoru",
    "Always use the selected search engine through Xylune's client-side web_search tool." to "Her zaman Xylune'un istemci tarafı web_search aracı üzerinden seçili arama motorunu kullanır.",
    "No API key. Uses DuckDuckGo's lightweight HTML results endpoint." to "API anahtarı gerekmez. DuckDuckGo'nun hafif HTML sonuç uç noktasını kullanır.",
    "Uses the official Brave Search API." to "Resmî Brave Search API'sini kullanır.",
    "Search API optimized for AI research and concise result content." to "Yapay zekâ araştırması ve kısa sonuç içeriği için optimize edilmiş arama API'si.",
    "Google-result API supplied by Serper." to "Serper tarafından sağlanan Google sonuç API'si.",
    "Uses a user-supplied public HTTPS SearXNG instance with JSON output enabled." to "JSON çıktısı etkin, kullanıcı tarafından sağlanan genel bir HTTPS SearXNG sunucusu kullanır.",
    "Unavailable" to "Kullanılamıyor",
    "Min" to "Min",
    "Low" to "Düşük",
    "Med" to "Orta",
    "High" to "Yüksek",
    "XHigh" to "Çok yüksek",
    "Max" to "Maks",
    "Fastest, light reasoning" to "En hızlı, hafif akıl yürütme",
    "Short reasoning" to "Kısa akıl yürütme",
    "Balanced" to "Dengeli",
    "More thorough reasoning" to "Daha kapsamlı akıl yürütme",
    "Extended reasoning" to "Genişletilmiş akıl yürütme",
    "Maximum supported reasoning" to "Desteklenen en yüksek akıl yürütme",
    "Code" to "Kod",
    "2 on" to "2 açık",
    "Research in progress" to "Araştırma sürüyor",
    "Research state reported" to "Araştırma durumu bildirildi",
    "Planning" to "Planlanıyor",
    "Researching" to "Araştırılıyor",
    "Writing report" to "Rapor yazılıyor",
    "Complete" to "Tamamlandı",
    "Blocked" to "Engellendi",
    "Starting" to "Başlatılıyor",
    "Unreported" to "Bildirilmedi",
    "Archived" to "Arşivlenmiş",
    "PROJECTS" to "PROJELER",
    "Backups" to "Yedekler",
    "Bucket" to "Kova",
    "Cloud" to "Bulut",
    "Compress" to "Sıkıştır",
    "Connected" to "Bağlı",
    "Copy report" to "Raporu kopyala",
    "Details" to "Ayrıntılar",
    "Dismiss" to "Kapat",
    "File" to "Dosya",
    "Flat" to "Düz",
    "Input" to "Girdi",
    "Instructions" to "Talimatlar",
    "Label" to "Etiket",
    "Linux workspace not ready" to "Linux çalışma alanı hazır değil",
    "Models" to "Modeller",
    "Output" to "Çıktı",
    "Override" to "Geçersiz kıl",
    "Overview" to "Genel bakış",
    "Package" to "Paket",
    "Photos" to "Fotoğraflar",
    "Prefix" to "Önek",
    "Prepend" to "Başa ekle",
    "Preview" to "Önizle",
    "Pricing" to "Fiyatlandırma",
    "Reconnect" to "Yeniden bağlan",
    "Region" to "Bölge",
    "Repair" to "Onar",
    "Review" to "İncele",
    "Rounded" to "Yuvarlatılmış",
    "running…" to "çalışıyor…",
    "Runtimes" to "Çalışma zamanları",
    "Source" to "Kaynak",
    "Terms" to "Koşullar",
    "Try full rendering again" to "Tam işlemeyi yeniden dene",
    "Usage" to "Kullanım",
    "Use chart JSON or `label: value` lines." to "Grafik JSON'u veya `etiket: değer` satırlarını kullanın.",
    "Username" to "Kullanıcı adı",
    "Follow device" to "Cihazı izle",
    "Developer options" to "Geliştirici seçenekleri",
    "Developer options · enabled" to "Geliştirici seçenekleri · etkin",
    "No provider selected" to "Sağlayıcı seçilmedi",
    "Choose automation model" to "Otomasyon modeli seç",
    "Selected" to "Seçildi",
    "New project" to "Yeni proje",
    "Clear search" to "Aramayı temizle",
    "Save a copy" to "Bir kopya kaydet",
    "Zoom out" to "Uzaklaştır",
    "Zoom in" to "Yakınlaştır",
    "Fit image" to "Görseli sığdır",
    "Previous page" to "Önceki sayfa",
    "Next page" to "Sonraki sayfa",
    "Close model picker" to "Model seçiciyi kapat",
    "Stop image generation" to "Görsel oluşturmayı durdur",
    "Previous text page" to "Önceki metin sayfası",
    "Next text page" to "Sonraki metin sayfası",
    "Previous extracted-text page" to "Önceki çıkarılmış metin sayfası",
    "Next extracted-text page" to "Sonraki çıkarılmış metin sayfası",
    "Delete backup" to "Yedeği sil",
    "Previous setup step" to "Önceki kurulum adımı",
    "Run in workspace" to "Çalışma alanında çalıştır",
    "Run with Linux tools" to "Linux araçlarıyla çalıştır",
    "Edit memory" to "Belleği düzenle",
    "Delete memory" to "Belleği sil",
    "Rename provider" to "Sağlayıcıyı yeniden adlandır",
    "Refresh usage" to "Kullanımı yenile",
    "Open conversations" to "Sohbetleri aç",
    "Add reference image" to "Referans görsel ekle",
    "Message actions" to "Mesaj işlemleri",
    "Open full-screen preview" to "Tam ekran önizlemeyi aç",
    "Conversations" to "Sohbetler",
    "Chat actions" to "Sohbet işlemleri",
    "Go to latest message" to "En son mesaja git",
    "Dismiss error" to "Hatayı kapat",
    "Retry response" to "Yanıtı yeniden dene",
    "Previous branch" to "Önceki dal",
    "Next branch" to "Sonraki dal",
    "Choose thinking level" to "Düşünme düzeyini seç",
    "Choose search mode" to "Arama modunu seç",
    "Choose chat tools" to "Sohbet araçlarını seç",
    "Choose folder" to "Klasör seç",
    "Back to runtime manager" to "Çalışma zamanı yöneticisine dön",
    "Clear terminal" to "Terminali temizle",
    "Run" to "Çalıştır",
    "Inspect repair" to "Onarımı incele",
    "Xylune recovered a crash report" to "Xylune bir çökme raporu kurtardı",
    "Xylune reopened safely with generated widgets paused. Your chats and files were not deleted. You can dismiss this report and keep using the app, then retry full rendering when ready." to "Xylune, oluşturulan widget'lar duraklatılmış güvenli modda yeniden açıldı. Sohbetleriniz ve dosyalarınız silinmedi. Bu raporu kapatıp uygulamayı kullanmaya devam edebilir, hazır olduğunuzda tam işlemeyi yeniden deneyebilirsiniz.",
    "Copy this redacted diagnostic report if you need help diagnosing the failure. Review it before sharing." to "Sorunu tanılamak için yardıma ihtiyacınız varsa bu ayıklanmış tanılama raporunu kopyalayın. Paylaşmadan önce gözden geçirin.",
    "Xylune core prompt only" to "Yalnızca Xylune çekirdek istemi",
    "Managed by Xylune" to "Xylune tarafından yönetiliyor",
    "Protocol" to "Protokol",
    "Build variable" to "Derleme değişkeni",
    "Redirect URI" to "Yönlendirme URI'si",
    "A source used to support this response." to "Bu yanıtı desteklemek için kullanılan bir kaynak.",
    "Search off" to "Arama kapalı",
    "API" to "API",
    "ChatGPT" to "ChatGPT",
    "DeepSeek Chat" to "DeepSeek Chat",
    "Python" to "Python",
    "Linux" to "Linux",
    "Generated image" to "Oluşturulan görsel",
    "Sent file" to "Gönderilen dosya",
    "Current generated image preview" to "Oluşturulan mevcut görsel önizlemesi",
    "Choose the language Xylune uses. System default follows Android." to "Xylune'un kullanacağı dili seçin. Sistem varsayılanı Android dilini izler.",
    "App language" to "Uygulama dili",
    "Follow Android language" to "Android dilini izle",
    "1–600 seconds. Pure Python is interrupted at the deadline; a blocking native extension may return later." to "1–600 saniye. Saf Python süre sınırında kesilir; engelleyen yerel bir eklenti daha sonra dönebilir.",
    "3–20 results per search call" to "Arama çağrısı başına 3–20 sonuç",
    "A native home-screen widget generated in an Xylune conversation" to "Bir Xylune sohbetinde oluşturulan yerel Ana ekran widget'ı",
    "A pair is one request plus its answer. Working history has its own budget inside the total context ceiling." to "Bir çift, bir istek ve yanıtından oluşur. Çalışma geçmişinin toplam bağlam sınırı içinde ayrı bir bütçesi vardır.",
    "A permissioned programmable Home-screen widget created by Xylune" to "Xylune tarafından oluşturulan izinli programlanabilir Ana ekran widget'ı",
    "About" to "Hakkında",
    "About Xylune" to "Xylune hakkında",
    "Access key ID" to "Erişim anahtarı kimliği",
    "Add" to "Ekle",
    "Add a ChatGPT account or configure an API-compatible provider." to "Bir ChatGPT hesabı ekleyin veya API uyumlu bir sağlayıcı yapılandırın.",
    "Add a usable provider in the Providers tab." to "Sağlayıcılar sekmesinden kullanılabilir bir sağlayıcı ekleyin.",
    "Add another" to "Bir tane daha ekle",
    "Add API" to "API ekle",
    "Add ChatGPT" to "ChatGPT ekle",
    "Add ChatGPT provider" to "ChatGPT sağlayıcısı ekle",
    "Add configured widget" to "Yapılandırılmış widget ekle",
    "Add image" to "Görsel ekle",
    "Add memory" to "Bellek ekle",
    "Add model" to "Model ekle",
    "Add provider" to "Sağlayıcı ekle",
    "Add to chat" to "Sohbete ekle",
    "Add your first API provider" to "İlk API sağlayıcınızı ekleyin",
    "Advanced compatibility" to "Gelişmiş uyumluluk",
    "Advanced headers" to "Gelişmiş üst bilgiler",
    "Advanced package sources" to "Gelişmiş paket kaynakları",
    "AI responses" to "Yapay zekâ yanıtları",
    "All" to "Tümü",
    "All categories" to "Tüm kategoriler",
    "All chats" to "Tüm sohbetler",
    "All providers" to "Tüm sağlayıcılar",
    "Allow and install" to "İzin ver ve yükle",
    "Allow models to save stable, non-sensitive details; duplicate items are merged" to "Modellerin kalıcı ve hassas olmayan ayrıntıları kaydetmesine izin ver; yinelenen öğeler birleştirilir",
    "Allow package changes?" to "Paket değişikliklerine izin verilsin mi?",
    "Allow package installation?" to "Paket kurulumuna izin verilsin mi?",
    "Allow page fetching" to "Sayfa getirmeye izin ver",
    "Allow pip direct references and relaxed apt names; command-line options remain blocked" to "pip doğrudan referanslarına ve esnek apt adlarına izin ver; komut satırı seçenekleri yine engellenir",
    "Always" to "Her zaman",
    "AMOLED black" to "AMOLED siyah",
    "AMOLED black only changes dark mode surfaces." to "AMOLED siyah yalnızca koyu mod yüzeylerini değiştirir.",
    "Android may delay work to protect battery." to "Android pili korumak için işi geciktirebilir.",
    "API base URL" to "API temel URL'si",
    "API key" to "API anahtarı",
    "API key (optional)" to "API anahtarı (isteğe bağlı)",
    "API model ID" to "API model kimliği",
    "Appearance" to "Görünüm",
    "Archive password" to "Arşiv parolası",
    "Ask AI to retry" to "Yapay zekâdan yeniden denemesini iste",
    "Ask every time" to "Her seferinde sor",
    "Assistant responses" to "Asistan yanıtları",
    "Auto" to "Otomatik",
    "Automatic checks are unavailable because this build has no embedded GitHub repository origin." to "Bu derlemede gömülü GitHub depo kaynağı bulunmadığından otomatik denetimler kullanılamıyor.",
    "Automatic memory" to "Otomatik bellek",
    "Automatic repair attempts" to "Otomatik onarım denemeleri",
    "Available levels follow the selected model. Some models cannot fully disable reasoning." to "Kullanılabilir düzeyler seçili modele bağlıdır. Bazı modellerde akıl yürütme tamamen kapatılamaz.",
    "Avoid decorative emoji and use them only when they add meaning" to "Süs amaçlı emojilerden kaçın ve yalnızca anlam kattıklarında kullan",
    "Back" to "Geri",
    "Back up now" to "Şimdi yedekle",
    "Background task models" to "Arka plan görevi modelleri",
    "Background tasks" to "Arka plan görevleri",
    "Backup & transfer" to "Yedekleme ve aktarım",
    "Base URL" to "Temel URL",
    "Before the first install" to "İlk kurulumdan önce",
    "Bugs, regressions, and feature requests" to "Hatalar, gerilemeler ve özellik istekleri",
    "Build information" to "Derleme bilgileri",
    "Build source" to "Derleme kaynağı",
    "Bundled Python 3.12 · no Linux download required" to "Paketlenmiş Python 3.12 · Linux indirmesi gerekmez",
    "Bundled suggestions" to "Paketlenmiş öneriler",
    "Cached input" to "Önbelleğe alınmış girdi",
    "Camera" to "Kamera",
    "Cancel" to "İptal",
    "Category" to "Kategori",
    "Cause profiler" to "Neden profilleyici",
    "Change folder" to "Klasörü değiştir",
    "Chat" to "Sohbet",
    "Chat behavior" to "Sohbet davranışı",
    "Chat configuration" to "Sohbet yapılandırması",
    "Chat naming" to "Sohbet adlandırma",
    "Chat naming and context compression models" to "Sohbet adlandırma ve bağlam sıkıştırma modelleri",
    "ChatGPT sign-in failed" to "ChatGPT oturum açma başarısız",
    "ChatGPT usage could not be loaded" to "ChatGPT kullanımı yüklenemedi",
    "Check again" to "Tekrar kontrol et",
    "Check automatically" to "Otomatik denetle",
    "Check for updates" to "Güncellemeleri denetle",
    "Check the source repository once per day when Xylune starts" to "Xylune başladığında kaynak depoyu günde bir kez denetle",
    "Checking…" to "Kontrol ediliyor…",
    "Choose a backup" to "Yedek seç",
    "Choose a backup folder" to "Yedek klasörü seç",
    "Choose a model" to "Model seç",
    "Choose a provider, then manage its connection and models." to "Bir sağlayıcı seçin, ardından bağlantısını ve modellerini yönetin.",
    "Choose a restrained built-in palette or Android dynamic colors. Every swatch is rendered from that palette, not the currently selected one." to "Dengeli bir yerleşik palet veya Android dinamik renklerini seçin. Her renk örneği, o anda seçili paletten değil kendi paletinden oluşturulur.",
    "Choose a rootless user-space distribution for broader third-party CLIs and libraries. Each distribution keeps its own packages, shares this chat's files at /workspace, and is a compatibility layer—not a security boundary." to "Daha geniş üçüncü taraf CLI ve kitaplık desteği için rootsuz bir kullanıcı alanı dağıtımı seçin. Her dağıtım kendi paketlerini tutar, bu sohbetin dosyalarını /workspace altında paylaşır ve bir uyumluluk katmanıdır; güvenlik sınırı değildir.",
    "Choose a scoped Android folder, an OAuth app folder, WebDAV/Nextcloud, or an S3-compatible bucket prefix. Xylune avoids account-wide cloud access." to "Kapsamlı bir Android klasörü, OAuth uygulama klasörü, WebDAV/Nextcloud veya S3 uyumlu kova öneki seçin. Xylune hesap genelinde bulut erişiminden kaçınır.",
    "Choose how Xylune names chats and compresses older context." to "Xylune'un sohbetleri nasıl adlandıracağını ve eski bağlamı nasıl sıkıştıracağını seçin.",
    "Choose one folder" to "Bir klasör seç",
    "Choose one or more reference images" to "Bir veya daha fazla referans görsel seç",
    "Choose whether Xylune follows Android or stays light or dark." to "Xylune'un Android'i izlemesini ya da açık veya koyu modda kalmasını seçin.",
    "Clear" to "Temizle",
    "Clear run state" to "Çalıştırma durumunu temizle",
    "Clear summary" to "Özeti temizle",
    "Close" to "Kapat",
    "Cloud & file backup" to "Bulut ve dosya yedekleme",
    "Cloud backups, local archives, and restore" to "Bulut yedekleri, yerel arşivler ve geri yükleme",
    "Cloud folder" to "Bulut klasörü",
    "Collapse complete plan" to "Tam planı daralt",
    "Collapse package plan" to "Paket planını daralt",
    "Collapse plan" to "Planı daralt",
    "Collapse source" to "Kaynağı daralt",
    "Color scheme" to "Renk düzeni",
    "Comma, space, or newline separated" to "Virgül, boşluk veya yeni satırla ayırın",
    "Compile & use" to "Derle ve kullan",
    "Composer defaults" to "Yazma alanı varsayılanları",
    "Compressed context active" to "Sıkıştırılmış bağlam etkin",
    "Configure a usable provider to enable model-based automation." to "Model tabanlı otomasyonu etkinleştirmek için kullanılabilir bir sağlayıcı yapılandırın.",
    "Configured in USD per million tokens" to "Milyon token başına USD olarak yapılandırılır",
    "Confirm password" to "Parolayı doğrula",
    "Connect & fetch models" to "Bağlan ve modelleri getir",
    "Connect a provider" to "Sağlayıcı bağla",
    "Connect folder" to "Klasörü bağla",
    "Connect Google Drive" to "Google Drive'a bağlan",
    "Connecting…" to "Bağlanıyor…",
    "Connection details stay out of the way until you need them." to "Bağlantı ayrıntıları gerekene kadar gizli kalır.",
    "Context & output" to "Bağlam ve çıktı",
    "Context compression" to "Bağlam sıkıştırma",
    "Context tokens" to "Bağlam tokenları",
    "Continue" to "Devam et",
    "Continue without one" to "Sağlayıcı olmadan devam et",
    "Controls how Xylune handles AI-generated interactive UI." to "Xylune'un yapay zekâ tarafından oluşturulan etkileşimli arayüzleri nasıl işleyeceğini belirler.",
    "Controls whether reasoning and tool cards expand automatically; they remain saved either way." to "Akıl yürütme ve araç kartlarının otomatik genişleyip genişlemeyeceğini belirler; her iki durumda da kaydedilirler.",
    "Controls whether this custom endpoint uses chat/completions or images/generations." to "Bu özel uç noktanın chat/completions mı yoksa images/generations mı kullanacağını belirler.",
    "Copy" to "Kopyala",
    "Copy errors" to "Hataları kopyala",
    "Copy setup details" to "Kurulum ayrıntılarını kopyala",
    "Copy source" to "Kaynağı kopyala",
    "Created by @omerfaruknehir" to "@omerfaruknehir tarafından oluşturuldu",
    "Creating and uploading…" to "Oluşturuluyor ve yükleniyor…",
    "Credentials are encrypted with Android Keystore and are never included in Xylune backups." to "Kimlik bilgileri Android Keystore ile şifrelenir ve Xylune yedeklerine asla dahil edilmez.",
    "Credentials are encrypted with Android Keystore and sent only to the provider you choose." to "Kimlik bilgileri Android Keystore ile şifrelenir ve yalnızca seçtiğiniz sağlayıcıya gönderilir.",
    "Cross-chat facts and preferences stored locally" to "Sohbetler arasında kullanılan yerel bilgi ve tercihler",
    "Current OpenAI image generation and editing model" to "Güncel OpenAI görsel oluşturma ve düzenleme modeli",
    "Custom headers JSON" to "Özel üst bilgi JSON'u",
    "Custom instructions" to "Özel talimatlar",
    "Custom provider" to "Özel sağlayıcı",
    "Dark" to "Koyu",
    "Data deletion" to "Veri silme",
    "Date" to "Tarih",
    "Deep Research" to "Derin Araştırma",
    "Deep Research plans, searches iteratively, verifies sources, and produces a cited report. Enabling it also enables web search." to "Derin Araştırma plan yapar, yinelemeli arama yapar, kaynakları doğrular ve kaynak gösteren bir rapor üretir. Etkinleştirildiğinde web araması da açılır.",
    "Default" to "Varsayılan",
    "Delete" to "Sil",
    "Delete cloud backup?" to "Bulut yedeği silinsin mi?",
    "Delete disabled" to "Devre dışı olanları sil",
    "Delete local data and provider-held copies" to "Yerel verileri ve sağlayıcılardaki kopyaları sil",
    "Delete memory?" to "Bellek silinsin mi?",
    "Detailed metrics" to "Ayrıntılı ölçümler",
    "Direct HTTPS WebDAV support for Nextcloud, ownCloud, NAS servers, and compatible hosts. Use an app password when available." to "Nextcloud, ownCloud, NAS sunucuları ve uyumlu sistemler için doğrudan HTTPS WebDAV desteği. Mümkünse uygulama parolası kullanın.",
    "Disable" to "Devre dışı bırak",
    "Disable all" to "Tümünü devre dışı bırak",
    "Disable only for a trusted local or keyless endpoint" to "Yalnızca güvenilir yerel veya anahtarsız bir uç nokta için kapatın",
    "Disable only for your own local/keyless endpoint" to "Yalnızca kendi yerel/anahtarsız uç noktanız için kapatın",
    "Disabled memories are currently excluded from chats. This cleanup permanently removes them." to "Devre dışı bellekler şu anda sohbetlere dahil edilmez. Bu temizlik onları kalıcı olarak kaldırır.",
    "Disconnect" to "Bağlantıyı kes",
    "Display name" to "Görünen ad",
    "Done" to "Bitti",
    "Download update" to "Güncellemeyi indir",
    "Each chat has a persistent bundled-Python session and isolated .packages directory. It works without installing Linux and remains confined by Android's app sandbox." to "Her sohbetin kalıcı paketlenmiş Python oturumu ve yalıtılmış .packages dizini vardır. Linux kurulmadan çalışır ve Android uygulama sanal alanı içinde kalır.",
    "Each provider keeps its OAuth session, models, usage limits, and refresh state separate. Xylune requests a fresh sign-in page so you can add a different ChatGPT account." to "Her sağlayıcı OAuth oturumunu, modellerini, kullanım sınırlarını ve yenileme durumunu ayrı tutar. Farklı bir ChatGPT hesabı ekleyebilmeniz için Xylune yeni bir oturum açma sayfası ister.",
    "Edge softness" to "Kenar yumuşaklığı",
    "Edit" to "Düzenle",
    "Edit connection" to "Bağlantıyı düzenle",
    "Edit custom profile" to "Özel profili düzenle",
    "Edit message" to "Mesajı düzenle",
    "Edit model" to "Modeli düzenle",
    "Edit source" to "Kaynağı düzenle",
    "Emoji use and global answer presentation" to "Emoji kullanımı ve genel yanıt sunumu",
    "Enable" to "Etkinleştir",
    "Enable all" to "Tümünü etkinleştir",
    "Enable developer settings" to "Geliştirici ayarlarını etkinleştir",
    "Encryption password (optional)" to "Şifreleme parolası (isteğe bağlı)",
    "English" to "İngilizce",
    "Enter the exact HTTPS URL of a dedicated Xylune folder. For Nextcloud this normally ends with /remote.php/dav/files/USERNAME/Xylune/." to "Xylune'a ayrılmış klasörün tam HTTPS URL'sini girin. Nextcloud için bu genellikle /remote.php/dav/files/KULLANICIADI/Xylune/ ile biter.",
    "Enter Xylune" to "Xylune'a gir",
    "Execution deadline (seconds)" to "Çalıştırma süre sınırı (saniye)",
    "Expose selected enabled memories to chats and allow memory tools" to "Seçili etkin bellekleri sohbetlere sun ve bellek araçlarına izin ver",
    "Expose web_fetch so the model can read public HTTPS pages after searching." to "Modelin aramadan sonra genel HTTPS sayfalarını okuyabilmesi için web_fetch aracını sun.",
    "Fallback search engine" to "Yedek arama motoru",
    "Fetch models again" to "Modelleri yeniden getir",
    "Fetched source" to "Getirilen kaynak",
    "FILE" to "DOSYA",
    "Sent file" to "Gönderilen dosya",
    "installed" to "yüklü",
    "install" to "yükle",
    "remove" to "kaldır",
    "upgrade" to "yükselt",
    "downgrade" to "düşür",
    "keep" to "koru",
    "repeated candidate" to "yinelenen aday",
    "partial cost" to "kısmi maliyet",
    "tokens" to "token",
    "Files" to "Dosyalar",
    "Finish setup" to "Kurulumu tamamla",
    "Generated content" to "Oluşturulan içerik",
    "generated content errors" to "oluşturulan içerik hataları",
    "Generated rendering disabled after a crash." to "Bir çökmeden sonra oluşturulan içerik işleme devre dışı bırakıldı.",
    "generated source" to "oluşturulan kaynak",
    "Generated UI safety and local-data behavior" to "Oluşturulan arayüz güvenliği ve yerel veri davranışı",
    "Google Drive" to "Google Drive",
    "Google Drive authorization failed" to "Google Drive yetkilendirmesi başarısız",
    "Google Drive backup failed" to "Google Drive yedeklemesi başarısız",
    "Google Drive connection canceled" to "Google Drive bağlantısı iptal edildi",
    "Google Drive setup required" to "Google Drive kurulumu gerekli",
    "Google Drive, OneDrive, Nextcloud, USB, or local storage through Android" to "Android üzerinden Google Drive, OneDrive, Nextcloud, USB veya yerel depolama",
    "Guide thickness" to "Kılavuz kalınlığı",
    "Hide attempts" to "Denemeleri gizle",
    "Hide manual model entry" to "Elle model girişini gizle",
    "Hide OCR overlay" to "OCR katmanını gizle",
    "HTTPS endpoint" to "HTTPS uç noktası",
    "HTTPS GET only" to "Yalnızca HTTPS GET",
    "Hybrid preflight counting" to "Hibrit ön sayım",
    "Hybrid token counting" to "Hibrit token sayımı",
    "Image generation" to "Görsel oluşturma",
    "Images" to "Görseller",
    "Import and continue" to "İçe aktar ve devam et",
    "Import backup" to "Yedeği içe aktar",
    "In use" to "Kullanımda",
    "Included content" to "Dahil edilen içerik",
    "Included modules" to "Dahil edilen modüller",
    "Install packages" to "Paketleri yükle",
    "Intelligence" to "Zekâ",
    "Interactive preview" to "Etkileşimli önizleme",
    "Interactive snippet" to "Etkileşimli parça",
    "Interface panels" to "Arayüz panelleri",
    "Interrupted response" to "Kesintiye uğramış yanıt",
    "Invalid completed widgets, charts, and diagrams are repaired in place up to this limit." to "Geçersiz tamamlanmış widget, grafik ve diyagramlar bu sınıra kadar yerinde onarılır.",
    "Its encrypted OAuth session and models will be disconnected. Chats and usage history are kept." to "Şifrelenmiş OAuth oturumunun ve modellerinin bağlantısı kesilir. Sohbetler ve kullanım geçmişi korunur.",
    "Its saved API key will be erased and it will disappear from model selectors. Chats and usage history are kept." to "Kayıtlı API anahtarı silinir ve sağlayıcı model seçicilerden kaldırılır. Sohbetler ve kullanım geçmişi korunur.",
    "Keep data current" to "Verileri güncel tut",
    "Keep in background" to "Arka planda tut",
    "Keep the partial answer" to "Kısmi yanıtı koru",
    "Language" to "Dil",
    "Legacy lower-cost OpenAI image model" to "Eski, daha düşük maliyetli OpenAI görsel modeli",
    "Legacy OpenAI image model" to "Eski OpenAI görsel modeli",
    "Less emoji" to "Daha az emoji",
    "Licenses & notices" to "Lisanslar ve bildirimler",
    "Light" to "Açık",
    "Linux commands" to "Linux komutları",
    "Linux execution" to "Linux çalıştırma",
    "Linux package request" to "Linux paket isteği",
    "Linux workspace" to "Linux çalışma alanı",
    "Linux workspace not installed" to "Linux çalışma alanı kurulu değil",
    "Live output updates as the process prints." to "İşlem çıktı ürettikçe canlı çıktı güncellenir.",
    "Loading preview…" to "Önizleme yükleniyor…",
    "Loading usage…" to "Kullanım yükleniyor…",
    "Local" to "Yerel",
    "Local Code Execution" to "Yerel Kod Çalıştırma",
    "Local execution" to "Yerel çalıştırma",
    "Local image description" to "Yerel görsel açıklaması",
    "Manage Linux workspace" to "Linux çalışma alanını yönet",
    "Manage providers" to "Sağlayıcıları yönet",
    "Manual" to "Elle",
    "Manual memories are available immediately and use the same deduplication rules." to "Elle eklenen bellekler hemen kullanılabilir ve aynı yinelenenleri birleştirme kurallarını kullanır.",
    "Manual model will also be included" to "Elle girilen model de dahil edilecek",
    "Match launcher icon to palette" to "Başlatıcı simgesini paletle eşleştir",
    "Max output" to "Maksimum çıktı",
    "Maximum search results" to "Maksimum arama sonucu",
    "Memory" to "Bellek",
    "Model" to "Model",
    "Model capabilities and request transport are selected automatically by this provider preset." to "Model yetenekleri ve istek aktarımı bu sağlayıcı ön ayarı tarafından otomatik seçilir.",
    "Model display name" to "Model görünen adı",
    "Model mode considers newer messages whenever a name is regenerated." to "Model modu, ad yeniden oluşturulduğunda daha yeni mesajları dikkate alır.",
    "Model, thinking, context, and output limits" to "Model, düşünme, bağlam ve çıktı sınırları",
    "Models discovered for this ChatGPT account only." to "Yalnızca bu ChatGPT hesabı için bulunan modeller.",
    "Models from provider" to "Sağlayıcıdaki modeller",
    "My DeepSeek account" to "DeepSeek hesabım",
    "Name" to "Ad",
    "Native Android BYOK model workspace." to "Yerel Android BYOK model çalışma alanı.",
    "Native routing, search engines, credentials, and page fetching" to "Yerel yönlendirme, arama motorları, kimlik bilgileri ve sayfa getirme",
    "Never" to "Asla",
    "New chat" to "Yeni sohbet",
    "New chat defaults" to "Yeni sohbet varsayılanları",
    "New conversation" to "Yeni sohbet",
    "New custom profile" to "Yeni özel profil",
    "Newest" to "En yeni",
    "Next" to "İleri",
    "Nextcloud / WebDAV" to "Nextcloud / WebDAV",
    "No GitHub source was embedded in this build" to "Bu derlemeye GitHub kaynak bilgisi gömülmemiş",
    "No inline preview for this file type" to "Bu dosya türü için satır içi önizleme yok",
    "No matches" to "Eşleşme yok",
    "No matching components" to "Eşleşen bileşen yok",
    "No matching models." to "Eşleşen model yok.",
    "No providers yet" to "Henüz sağlayıcı yok",
    "No saved prompts yet." to "Henüz kayıtlı istem yok.",
    "OCR on" to "OCR açık",
    "Off" to "Kapalı",
    "Offline dependency catalog and full license texts" to "Çevrimdışı bağımlılık kataloğu ve tam lisans metinleri",
    "Older messages outside the active context window are merged into saved compact context." to "Etkin bağlam penceresinin dışındaki eski mesajlar kaydedilmiş sıkıştırılmış bağlama birleştirilir.",
    "Oldest" to "En eski",
    "On" to "Açık",
    "On-device history • BYOK" to "Cihazdaki geçmiş • BYOK",
    "One package requirement per line. Xylune resolves Android-compatible Python 3.12 wheels before applying your approval policy." to "Her satıra bir paket gereksinimi yazın. Xylune, onay politikanızı uygulamadan önce Android uyumlu Python 3.12 wheel paketlerini çözümler.",
    "One searchable catalog is used everywhere in Xylune." to "Xylune'un her yerinde tek bir aranabilir katalog kullanılır.",
    "Only missing or outdated packages will be changed. Packages and install scripts run with Xylune's app permissions." to "Yalnızca eksik veya eski paketler değiştirilir. Paketler ve kurulum betikleri Xylune'un uygulama izinleriyle çalışır.",
    "Only missing or outdated packages will change. Install scripts run with Xylune's app permissions." to "Yalnızca eksik veya eski paketler değişir. Kurulum betikleri Xylune'un uygulama izinleriyle çalışır.",
    "Only the essentials are shown. Pricing is optional." to "Yalnızca temel alanlar gösterilir. Fiyatlandırma isteğe bağlıdır.",
    "Only the selected provider models will be saved." to "Yalnızca seçilen sağlayıcı modelleri kaydedilecek.",
    "Open" to "Aç",
    "Open OCR view" to "OCR görünümünü aç",
    "Open provider setup guide" to "Sağlayıcı kurulum rehberini aç",
    "Open release page" to "Sürüm sayfasını aç",
    "Open runtime manager" to "Çalışma zamanı yöneticisini aç",
    "Open setup guide" to "Kurulum rehberini aç",
    "Open the creator's GitHub profile" to "Geliştiricinin GitHub profilini aç",
    "OpenAI compatible" to "OpenAI uyumlu",
    "OpenAI-compatible" to "OpenAI uyumlu",
    "Optional hybrid preflight counting. Provider count endpoints are preferred; local model-family estimates and the generic estimator are fallbacks." to "İsteğe bağlı hibrit ön sayım. Sağlayıcının sayım uç noktaları tercih edilir; yerel model ailesi tahminleri ve genel tahminleyici yedek olarak kullanılır.",
    "Optional · cost will show as unavailable" to "İsteğe bağlı · girilmezse maliyet kullanılamıyor olarak görünür",
    "Overlay position" to "Katman konumu",
    "Overlay scale" to "Katman ölçeği",
    "Panel opacity" to "Panel opaklığı",
    "Panel shape" to "Panel şekli",
    "Panel shape is a choice. Blur, softness, and tint remain continuous controls." to "Panel şekli ayrı bir seçimdir. Bulanıklık, kenar yumuşaklığı ve ton sürekli ayarlardır.",
    "Password or app password" to "Parola veya uygulama parolası",
    "Password — leave blank for none" to "Parola — kullanmayacaksanız boş bırakın",
    "Passwords do not match" to "Parolalar eşleşmiyor",
    "Permissions and data access" to "İzinler ve veri erişimi",
    "Personalization" to "Kişiselleştirme",
    "Portable Xylune backup" to "Taşınabilir Xylune yedeği",
    "Preflight & review" to "Ön kontrol ve inceleme",
    "Prepare OCR" to "OCR hazırla",
    "Preparing Xylune…" to "Xylune hazırlanıyor…",
    "Preview and import a backup" to "Yedeği önizle ve içe aktar",
    "Previous OpenAI image model" to "Önceki OpenAI görsel modeli",
    "Previously selected backup folder" to "Önceden seçilen yedek klasörü",
    "Pricing configured" to "Fiyatlandırma yapılandırıldı",
    "Privacy" to "Gizlilik",
    "Privacy & safety" to "Gizlilik ve güvenlik",
    "Privacy policy" to "Gizlilik politikası",
    "Privacy, local data, providers, and KVKK/GDPR boundaries" to "Gizlilik, yerel veriler, sağlayıcılar ve KVKK/GDPR sınırları",
    "Private by design" to "Tasarım gereği özel",
    "Private cloud targets" to "Özel bulut hedefleri",
    "Private Xylune app storage" to "Özel Xylune uygulama depolaması",
    "Programmable widget content" to "Programlanabilir widget içeriği",
    "Project website" to "Proje web sitesi",
    "Provider calls" to "Sağlayıcı çağrıları",
    "Provider has no model list? Enter manually" to "Sağlayıcının model listesi yok mu? Elle girin",
    "Provider name" to "Sağlayıcı adı",
    "Providers & models" to "Sağlayıcılar ve modeller",
    "Public HTTPS base URL" to "Genel HTTPS temel URL'si",
    "Python execution" to "Python çalıştırma",
    "Python is still running" to "Python hâlâ çalışıyor",
    "Python package request" to "Python paket isteği",
    "Python script" to "Python betiği",
    "Python workspace" to "Python çalışma alanı",
    "Python · Ready" to "Python · Hazır",
    "Python, Linux, packages, and approval policy" to "Python, Linux, paketler ve onay politikası",
    "Queue this message" to "Bu mesajı sıraya al",
    "Read license" to "Lisansı oku",
    "Refresh" to "Yenile",
    "Refresh backup list" to "Yedek listesini yenile",
    "Refresh models" to "Modelleri yenile",
    "Refresh widget" to "Widget'ı yenile",
    "Refreshing…" to "Yenileniyor…",
    "Regenerate chat name" to "Sohbet adını yeniden oluştur",
    "Remove" to "Kaldır",
    "Remove Linux runtime" to "Linux çalışma zamanını kaldır",
    "Remove provider" to "Sağlayıcıyı kaldır",
    "Rename ChatGPT provider" to "ChatGPT sağlayıcısını yeniden adlandır",
    "Rendering PDF…" to "PDF işleniyor…",
    "Report an issue" to "Sorun bildir",
    "Request error" to "İstek hatası",
    "Request type" to "İstek türü",
    "Require API key" to "API anahtarı iste",
    "Requires a separate distribution download" to "Ayrı bir dağıtım indirmesi gerektirir",
    "Research" to "Araştırma",
    "Research roadmap" to "Araştırma yol haritası",
    "Reset" to "Sıfırla",
    "Reset advanced values to defaults" to "Gelişmiş değerleri varsayılanlara sıfırla",
    "Response style" to "Yanıt stili",
    "Responses which continue while Xylune is in the background" to "Xylune arka plandayken devam eden yanıtlar",
    "Restore a backup" to "Yedeği geri yükle",
    "Restore an existing setup" to "Mevcut kurulumu geri yükle",
    "Retry" to "Yeniden dene",
    "Retry setup" to "Kurulumu yeniden dene",
    "Reusable tone and workflow profiles" to "Yeniden kullanılabilir üslup ve iş akışı profilleri",
    "Review and install changes" to "Değişiklikleri incele ve yükle",
    "Review required permissions" to "Gerekli izinleri incele",
    "Run details" to "Çalıştırma ayrıntıları",
    "Run failed" to "Çalıştırma başarısız",
    "Run Python in this chat's persistent workspace" to "Python'ı bu sohbetin kalıcı çalışma alanında çalıştır",
    "Running…" to "Çalışıyor…",
    "Runtime manager" to "Çalışma zamanı yöneticisi",
    "S3-compatible storage" to "S3 uyumlu depolama",
    "Safe generated rendering" to "Güvenli oluşturulan içerik işleme",
    "Save" to "Kaydet",
    "Save & regenerate" to "Kaydet ve yeniden oluştur",
    "Save and test" to "Kaydet ve test et",
    "Save backup" to "Yedeği kaydet",
    "Save connection" to "Bağlantıyı kaydet",
    "Save key" to "Anahtarı kaydet",
    "Save memory" to "Belleği kaydet",
    "Search" to "Ara",
    "Search & web" to "Arama ve web",
    "Search across every chat" to "Tüm sohbetlerde ara",
    "Search history" to "Geçmişte ara",
    "Search image models" to "Görsel modellerinde ara",
    "Search libraries or licenses" to "Kitaplık veya lisans ara",
    "Search memories" to "Belleklerde ara",
    "Search messages, code, and reasoning" to "Mesajlarda, kodda ve akıl yürütmede ara",
    "Search models" to "Modellerde ara",
    "Search PyPI" to "PyPI'da ara",
    "Searching…" to "Aranıyor…",
    "SearXNG endpoint" to "SearXNG uç noktası",
    "Secret access key" to "Gizli erişim anahtarı",
    "Select all" to "Tümünü seç",
    "Select shown" to "Gösterilenleri seç",
    "Selectable extracted content" to "Seçilebilir çıkarılmış içerik",
    "Selectable file preview" to "Seçilebilir dosya önizlemesi",
    "Selectable OCR text" to "Seçilebilir OCR metni",
    "Selected cloud folder" to "Seçili bulut klasörü",
    "Send after the current response finishes" to "Mevcut yanıt tamamlanınca gönder",
    "Send now" to "Şimdi gönder",
    "Session token (optional)" to "Oturum tokenı (isteğe bağlı)",
    "Set up a provider" to "Sağlayıcı kur",
    "Settings" to "Ayarlar",
    "Setup & connections" to "Kurulum ve bağlantılar",
    "Share" to "Paylaş",
    "Share message" to "Mesajı paylaş",
    "Share portable chat" to "Taşınabilir sohbeti paylaş",
    "Show backups" to "Yedekleri göster",
    "Show blur boundary guides" to "Bulanıklık sınır kılavuzlarını göster",
    "Show complete package plan" to "Tam paket planını göster",
    "Show OCR overlay" to "OCR katmanını göster",
    "Show package plan" to "Paket planını göster",
    "Show performance overlay" to "Performans katmanını göster",
    "Show source" to "Kaynağı göster",
    "Show tool diagnostics" to "Araç tanılamalarını göster",
    "Sign in again" to "Yeniden oturum aç",
    "Sign in with ChatGPT" to "ChatGPT ile oturum aç",
    "Signing SHA-1" to "İmzalama SHA-1",
    "Skip for now" to "Şimdilik atla",
    "Starred" to "Yıldızlı",
    "Start a response" to "Yanıt başlat",
    "Starting state for the controls beside the message box." to "Mesaj kutusunun yanındaki denetimlerin başlangıç durumu.",
    "Stop" to "Durdur",
    "Stop current response" to "Mevcut yanıtı durdur",
    "Stop requested by user." to "Kullanıcı durdurma istedi.",
    "Streaming…" to "Akış sürüyor…",
    "Switch account" to "Hesap değiştir",
    "System" to "Sistem",
    "System default" to "Sistem varsayılanı",
    "Take a photo to use as a reference" to "Referans olarak kullanmak için fotoğraf çek",
    "Tap a result to add it to the install list" to "Kurulum listesine eklemek için bir sonuca dokunun",
    "Tap to zoom" to "Yakınlaştırmak için dokun",
    "Terms & disclaimer" to "Koşullar ve sorumluluk reddi",
    "Text opacity" to "Metin opaklığı",
    "The Android document picker can save directly to Google Drive, OneDrive, Dropbox, Nextcloud, a USB drive, or local storage. Xylune does not upload through a hidden server." to "Android belge seçici doğrudan Google Drive, OneDrive, Dropbox, Nextcloud, USB sürücü veya yerel depolamaya kaydedebilir. Xylune gizli bir sunucu üzerinden yükleme yapmaz.",
    "The edited source is compiled, executed in the bounded runtime, and rendered before use." to "Düzenlenen kaynak kullanılmadan önce derlenir, sınırlandırılmış çalışma zamanında çalıştırılır ve işlenir.",
    "The generated program could not be read." to "Oluşturulan program okunamadı.",
    "The instance must enable JSON search output." to "Sunucuda JSON arama çıktısı etkin olmalıdır.",
    "The source and conversation are intact." to "Kaynak ve sohbet değişmeden duruyor.",
    "Theme mode" to "Tema modu",
    "Theme, palette, launcher icon, and AMOLED black" to "Tema, renk paleti, başlatıcı simgesi ve AMOLED siyah",
    "Thinking" to "Düşünme",
    "Thinking effort" to "Düşünme düzeyi",
    "This file is encrypted. Enter its password to inspect it." to "Bu dosya şifreli. İncelemek için parolasını girin.",
    "This permanently removes the selected memory data from Xylune." to "Bu işlem seçili bellek verisini Xylune'dan kalıcı olarak kaldırır.",
    "This removes the selected Linux root filesystem and its installed packages for all chats. Chat files in /workspace and bundled Python packages are kept." to "Bu işlem seçili Linux kök dosya sistemini ve yüklü paketlerini tüm sohbetler için kaldırır. /workspace içindeki sohbet dosyaları ve paketlenmiş Python paketleri korunur.",
    "Tint opacity" to "Ton opaklığı",
    "Token counting" to "Token sayımı",
    "Tool behavior" to "Araç davranışı",
    "Tool defaults" to "Araç varsayılanları",
    "Tools" to "Araçlar",
    "Tools & safety" to "Araçlar ve güvenlik",
    "Tools and modes" to "Araçlar ve modlar",
    "Trusted Linux packages (apt/apk)" to "Güvenilir Linux paketleri (apt/apk)",
    "Trusted pip packages" to "Güvenilir pip paketleri",
    "Try full rendering" to "Tam işlemeyi dene",
    "Turkish" to "Türkçe",
    "Type a message or attach a file first" to "Önce bir mesaj yazın veya dosya ekleyin",
    "Türkçe" to "Türkçe",
    "Unlock preview" to "Önizlemenin kilidini aç",
    "Update check failed" to "Güncelleme denetimi başarısız",
    "Update interval" to "Güncelleme aralığı",
    "Usage & limits" to "Kullanım ve sınırlar",
    "Usage details" to "Kullanım ayrıntıları",
    "Use a key restricted to this bucket and prefix. Credentials remain encrypted on-device." to "Bu kova ve önekle sınırlandırılmış bir anahtar kullanın. Kimlik bilgileri cihazda şifreli kalır.",
    "Use connected folder" to "Bağlı klasörü kullan",
    "Use for new chats" to "Yeni sohbetlerde kullan",
    "Use memory" to "Belleği kullan",
    "Use terms, third-party AI limits, warranty, and liability" to "Kullanım koşulları, üçüncü taraf yapay zekâ sınırları, garanti ve sorumluluk",
    "Use Xylune default for new chats" to "Yeni sohbetlerde Xylune varsayılanını kullan",
    "Uses Dropbox App folder access and scoped file permissions. Xylune cannot browse the rest of Dropbox." to "Dropbox Uygulama klasörü erişimini ve kapsamlı dosya izinlerini kullanır. Xylune Dropbox'ın geri kalanına göz atamaz.",
    "Uses OneDrive's Apps/Xylune folder with Files.ReadWrite.AppFolder instead of access to the whole drive." to "Tüm sürücüye erişmek yerine OneDrive'ın Apps/Xylune klasörünü Files.ReadWrite.AppFolder ile kullanır.",
    "Usually unnecessary" to "Genellikle gereksiz",
    "Version, architecture, and privacy model" to "Sürüm, mimari ve gizlilik modeli",
    "View attempts" to "Denemeleri göster",
    "Vision" to "Görsel",
    "Web search" to "Web araması",
    "WebDAV / Nextcloud" to "WebDAV / Nextcloud",
    "WebDAV folder URL" to "WebDAV klasör URL'si",
    "What this screen manages" to "Bu ekranın yönettikleri",
    "Work ChatGPT" to "İş ChatGPT",
    "Working display" to "Çalışma görünümü",
    "Working…" to "Çalışıyor…",
    "Works with AWS S3, Cloudflare R2, Backblaze B2, MinIO, and other Signature V4-compatible object stores." to "AWS S3, Cloudflare R2, Backblaze B2, MinIO ve diğer Signature V4 uyumlu nesne depolarıyla çalışır.",
    "Xylune generated widget" to "Xylune tarafından oluşturulan widget",
    "Xylune Google Drive OAuth setup" to "Xylune Google Drive OAuth kurulumu",
    "Xylune is up to date" to "Xylune güncel",
    "Xylune programmable widget" to "Xylune programlanabilir widget'ı",
    "Xylune stream error" to "Xylune akış hatası",
    "Xylune widget" to "Xylune widget'ı",
    "Xylune's green Material palette" to "Xylune'un yeşil Material paleti",
    "• A failed or interrupted setup can be retried; /workspace chat files are not deleted." to "• Başarısız veya kesilen kurulum yeniden denenebilir; /workspace sohbet dosyaları silinmez.",
    "• Linux installation, packages, terminal, and removal" to "• Linux kurulumu, paketler, terminal ve kaldırma",
    "• No Android root access is used or requested." to "• Android root erişimi kullanılmaz veya istenmez.",
    "• Requires a network download and app-private storage." to "• Ağdan indirme ve uygulamaya özel depolama gerektirir.",
    "• Runtime health and per-chat Python packages" to "• Çalışma zamanı durumu ve sohbet başına Python paketleri",
    "• Test runs only; chat tool permissions are controlled per chat" to "• Yalnızca test çalıştırmaları; sohbet araç izinleri sohbet başına yönetilir",
    "• Xylune verifies the archive before extraction and exposes progress for every stage." to "• Xylune arşivi çıkarmadan önce doğrular ve her aşamanın ilerlemesini gösterir.",
)
